### ISSUE TITLE
[Question] Contents of a database in memory?

### ISSUE THREAD

**Issue by brsunter** [ReSwift/ReSwift#117]
Hello,
I'm trying to use a database containing a fairly large number of elements (10,000+). I'm currently holding everything in memory, but this equates to 100+ mb of ram. Is there a best practice way of dealing with this? Ideally I would only like to load screenful of content at a time, but that would mean the state would not be a true representation of the app state

**Comment by Ben-G** [comment]
Hey @brsunter!

Thanks for the question. This has actually come up before (and should eventually make it into the readme). I've discussed a solution in #110. Can you check it out and see if it answers your question?

**Comment by brsunter** [comment]
Hey @Ben-G thanks for the response. I had a look at the thread and It looked like most of the discussion was about ways to keep the ReSwift state in sync with the DB state. However, my concern is having the entire contents of the database in memory when I only need certain parts of it at a given time. I was wondering if there were any best practices around having a database hold information that is not "mirrored" in the app state. I was thinking something along the lines of sending an action that loads subsets of information into the app state, but this breaks the idea that the app state is the single source of truth.
Sorry if this is a weird question, I was just wondering if anyone had given this any thought.

**Comment by ianterrell** [comment]
Hi @brsunter,

I'm reading all the open issues and came across this one. I think that @Ben-G's comments and the discussion on #110 do address this issue.

> I was wondering if there were any best practices around having a database hold information that is not "mirrored" in the app state. I was thinking something along the lines of sending an action that loads subsets of information into the app state...

I think that same idea is what's captured on #110:

> Treat the db similar to a webservice; as a failable outside resource. This would mean you would use ActionCreator or a similar concept to perform the db update before you update the state via reducers.

That would just mean that you'd query the database in the same manner that you'd query a webservice: perhaps in an ActionCreator, or in middleware (a la redux-saga), or in an extended store (a la redux-loop). Issue #64 has a great summary of options and some links to possible implementation ideas.

> ... but this breaks the idea that the app state is the single source of truth.

Personal opinion only, but I have been viewing app state as relating primarily to the state required to set up and manage the UI and user interaction. I do not view a database as part of the app state any more than I view a remote web service as part of the app state: they both contain information that my app may optionally use in its UI.

Hope this helps! 

Thanks,
Ian

**Comment by brsunter** [comment]
Hey Ian,
Thanks for the response. Still wrapping my head around the unidirectional model a little bit and your comment about only keeping the minimum of what's needed for the UI at a given time cleared things up for me. Getting something like redux loops looks like an amazing way to handle side effects btw.
