### ISSUE TITLE
Next ReSwift Release

### ISSUE THREAD

**Issue by Ben-G** [ReSwift/ReSwift#123]
This has been overdue since a while; the Swift 2.2 fixes need to be shipped. There are some breaking changes in the API around standard actions.

Even though these most likely only affect the `ReSwiftRecorder` we should choose a new major release version number in case we decide to ship the change. It's a very minor breaking change to `dictionaryRepresentation` of `StandardAction` so I want to see if it might make more sense to revert this change & defer it to a future major release along with more breaking changes.

Will look into this next week!

**Comment by agentk** [comment]
I think it's ok for a major version bump when the changes are going to break existing code for anybody.

The work to support swift 2.3 & 3.0 looks reasonably easy to do all in the one code base with the #if swift(>=3.0) defs. I'll have some time at the end of the week to pull together the changes if you like.

The `StandardAction` changes required quite a few changes to make my recorder work again. Mostly a lot of `nil` checking changes.

Jazzy has also just been released with the `Guides` support changes. It will take a bit of work automating the doc publishing though. I wouldn't like to see it block this release. Probably best to come back and look at if after.

**Comment by Ben-G** [comment]
@agentk I've opened a WIP PR #125 for the next release. I decided to make on change to `StandardAction` which handles the serialization of `nil` values. 

The `StandardAction` has some other improvements that are breaking changes; so this would be a 2.0.0 release. I've opened a branch on my recorder that updates it to reflect these changes.

I plan on wrapping this release up tonight / tomorrow.

**Comment by Ben-G** [comment]
Closing in favor of #125.
