### ISSUE TITLE
Remove SwiftLint from Pod

### ISSUE THREAD

**Issue by DarthRumata** [ReSwift/ReSwift#137]
I have my own ruleset for SwiftLint and your code can't pass it.
Please keep your code style trial on your local machine.

**Comment by agentk** [comment]
Sorry to hear that @DarthRumata. The `.swiftlint.yml` file in ReSwift is there for our automated code style testing. Removing it would be bad for all ReSwift contributors.

This is not an issue when ReSwift is used as a pod or carthage dependency, as YOUR root project `.swiftlint.yml` settings override it. Removing it from ReSwift will not make it pass your code style settings.

You might be best looking at the SwiftLint documentation and adding an exclude to your settings. Ie, in your `.swiftlint.yml`:

```yml
excluded: # paths to ignore during linting. overridden by `included`.
  - Pods
```

I'm going to close this for now. If I have misunderstood the question, I'm very sorry and please feel free to re-open the issue.

**Comment by DarthRumata** [comment]
Ok. Thanks for your reply. I will add swiftlint.yml to my project with excluded paths but I recommend you to publish some info in readme of ReSwift because initialising of SwiftLint script from external library is quiet unexpected.
