### ISSUE TITLE
Consolidating platform targets

### ISSUE THREAD

**Issue by samsonjs** [ReSwift/ReSwift#146]
I came across this post about how to make a multi-platform, single-scheme library: http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/

What do you all think about this? I can put in the work if it's something you may be interested in merging (I'm probably going to do it in my fork anyway). Just want to gauge interest and hear your thoughts about the idea. I'll also try it out in another small library, so I may have more to report after that's done.

**Comment by Ben-G** [comment]
@samsonjs At first, brief, glance this setup looks very cool! If you are already planning on doing it for your fork it would be awesome if you could suggest the changes back.

If this doesn't break Carthage/CocoaPods support, it looks like a superior setup compare to the current one IMO.

**Comment by agentk** [comment]
I really like the idea of smaller failure targets too. I'm interested. And we don't have any dependencies to worry about.  :-D

**Comment by DivineDominion** [comment]
@samsonjs any progress on this one? Sounds cool!

**Comment by samsonjs** [comment]
@DivineDominion I haven't tried to tackle this one yet. Took a detour at work in the fall and haven't been working with ReSwift for a while, but I will be back on my new app soon and still hope to give this a shot.
