### ISSUE TITLE
Not compiling with Carthage, Xcode 8 and Swift 3

### ISSUE THREAD

**Issue by buscarini** [ReSwift/ReSwift#152]
I'm trying to use ReSwift with the final Xcode 8 version and Carthage, but I can't get it to work:

`
*** Building scheme "ReSwift-iOS" in ReSwift.xcodeproj
** CLEAN FAILED **
The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/josanchez/prog/Audioguide/code/Carthage/Checkouts/ReSwift/ReSwift.xcodeproj -scheme ReSwift-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **
`

I guess this is a ReSwift error, because other frameworks build just fine.

**Comment by almasakchabayev** [comment]
Same here

**Comment by Ben-G** [comment]
See #153. The `master` branch has support for Xcode 8, but we still need to issue a new release. If you use `master` branch from Carthage you should be unblocked for now.

**Comment by Ben-G** [comment]
This should be fixed with #154. Please let me know if you're still running into issues!

**Comment by buscarini** [comment]
It works! thanks
