### ISSUE TITLE
Publish 2.1.0?

### ISSUE THREAD

**Issue by tpae** [ReSwift/ReSwift#155]
Hi, I noticed in Cocoapods repo (https://cocoapods.org/pods/ReSwift), it's still pointing to 2.0.0

Can you publish 2.1.0 please?

Thank you

**Comment by Ben-G** [comment]
@tpae My bad! I ran `pod spec lint` but forgot to run `pod trunk push` afterwards 😬

Thanks a lot for letting me know; it's been fixed now!
