### ISSUE TITLE
Binary (version 2.1.0) installed from Carthage is not compatible with Xcode 8.1 (Swift 3.0.1)

### ISSUE THREAD

**Issue by nixzhu** [ReSwift/ReSwift#164]
We need a new release.

**Comment by avocade** [comment]
👍

**Comment by Ben-G** [comment]
@nixzhu @avocade Thanks for the feedback! Binary releases are built via Travis, which doesn't have Xcode 8.1 support yet. We'll ship a new release once support is available. In the meantime I'd recommend using the latest release from source instead of binary.

**Comment by avocade** [comment]
Source works fine.

**Comment by Ben-G** [comment]
Just released 3.0.0 which has a pre-built framework that's built against Swift 3.0.1: https://github.com/ReSwift/ReSwift/releases/tag/3.0.0
