### ISSUE TITLE
Shouldn't StateType be named State?

### ISSUE THREAD

**Issue by hartbit** [ReSwift/ReSwift#170]
The Swift 3 API Design Guidelines and the changes in the Standard Library seem to point towards using plain names and using the `Protocol` suffix when necessary to reduce ambiguity. Worth considering?

**Comment by werediver** [comment]
In [the guide](https://swift.org/documentation/api-design-guidelines/) I see a note about `Type` suffix:

> If an associated type is so tightly bound to its protocol constraint that the protocol name is the role, avoid collision by appending Type to the associated type name ...

But I don't see such a note about the `Protocol` suffix. I understand the guide so as we should not suffix the protocols with anything. I don't think it's practical enough, though.

I **agree** that `StateType` (as well as anything suffixed with `Type`) doesn't follow the guide. Two possible ways to fix this are
- drop the `Type` suffix
- change the suffix to `Protocol`.

**Comment by Qata** [comment]
@agentk @Ben-G @DivineDominion What are your thoughts on this? I'm in favour of changing it.

**Comment by DivineDominion** [comment]
Me, too, but out of habit I'd simply drop the suffix and not replace it with `Protocol`.

**Comment by DivineDominion** [comment]
Anyone of you people fancy making a PR for this?

**Comment by DivineDominion** [comment]
Closing this refactoring suggestion for now. Feel free to reopen or suggest a PR.
