### ISSUE TITLE
Error handling in ReSwift

### ISSUE THREAD

**Issue by avdwerff** [ReSwift/ReSwift#173]
What would be a good way to handle generic errors in an application using ReSwift? 
I was thinking of dispatching router actions with data on (certain) error events. 
Anyone any experience or thoughts about architecting error flows with ReSwift?

**Comment by bbqsrc** [comment]
I use a state enum for handling these cases.

```swift
enum State<T, E> {
    case notStarted
    case loading
    case success(T)
    case failure(E)
}
```

When the state is `failure`, you handle it.

**Comment by avdwerff** [comment]
Ok, so do you handle this on a central place? If so how? Cause, for example an error might be translated to the user as a generic 'something went wrong, try again later' message.

**Comment by Qata** [comment]
If you want to present a message to the user, I'd recommend doing it in `Middleware` by intercepting a `.failure(_)` value.

**Comment by avdwerff** [comment]
@Qata Is it allowed for the middleware to infer with the view? Could show a simple example?

**Comment by Qata** [comment]
Well it's allowed but *should* it? ¯\\_(ツ)_/¯

```swift
let presentErrorMiddleware: Middleware = { dispatch, getState in
    return { next in
        return { action in
            switch action {
            case .PresentError(let error) as AppAction:
                let alert = UIAlertController(title: "Error", message: error.description, preferredStyle: .Alert)
                alert.addAction(UIAlertAction(title: "Okay", style: .Cancel, handler: nil))
                UIApplication.sharedApplication().keyWindow?.rootViewController?.presentViewController(alert, animated: true, completion: nil)
            default:
                break
            }
            return next(action)
        }
    }
}
```

**Comment by avdwerff** [comment]
Ok thanks for sharing.

**Comment by Qata** [comment]
@avdwerff Is your question answered to the point where it'd be okay if I close this issue?

**Comment by avdwerff** [comment]
Well, maybe not completely answered, but enough inspiration ;). Thanks.

**Comment by grundmanise** [comment]
@bbqsrc could you please share a simple example of how you use `enum` with `reducers` and `action creators`?
