### ISSUE TITLE
Protocols without `associatedtype` for store

### ISSUE THREAD

**Issue by dodikk** [ReSwift/ReSwift#174]
I'd like to inject the `StoreType` protocol as an ivar to my `ViewModel ==> Model ==> service` classes to let them dispatch the actions.

I'm experiencing the compiler errors similar to those described in the gist below.
https://gist.github.com/dodikk/d5d62002c6cf730c4b059215beeb9203

Having a protocol without the `associatedtype` would let me accomplish that just fine.

**Comment by dodikk** [comment]
I know there are some workarounds such as :

1. pass some lambda for dispatching - what if I use `ActionCreator` ?
2. use an explicit class - might be hard to pass some different type of a store in a unit test

Still, it would be better to use protocols, I guess.

**Comment by Qata** [comment]
If it's necessary that you have this ivar then you can use a generic type so that your ViewModel would look something like:

```swift
class ViewModel<Store: StoreType> {
    var store: Store
    init(store: Store) {
        self.store = store
    }
}
```

I'm not entirely sure why you're trying to use `StoreType`, your app shouldn't have multiple stores. If you're just trying to get a reference to the `Store` that your app is using then I'd recommend using a `typealias` instead. 

I'm going to close this since it's not an issue, we can't realistically remove the conformance without breaking functionality greatly, feel free to keep commenting if you run into issues with the workarounds though, it just won't be seen as a "bug" anymore.

**Comment by dodikk** [comment]
@Qata , I've reported an idea rather than a bug. It was not about removing the `associatedtype` from the StoreType protocol but about extracting some methods to a separate parent protocol. See the listing below

```swift
protocol StoreTypeStateless
{
    func dispatch(_ action: Action) -> Any
    func unsubscribe(_ subscriber: AnyStoreSubscriber)
   
    // other methods that do not involve associatedtype
}

protocol StoreType: StoreTypeStateless
{
    associatedtype State: StateType
    associatedtype DispatchCallback = (State) -> Void

    // rest of the stuff...
}
```

This does not seem to break anything and does not seem to require much effort.

P.S. So far I went with `[2] use an explicit class` approach

**Comment by dodikk** [comment]
> I'm not entirely sure why you're trying to use StoreType, your app shouldn't have multiple stores. 

Well, I'm trying to make the app modular and avoid putting the entire code base to a single target.
So I instantiate the store object in the app main module and inject it to other modules so that they would be able to dispatch events.

**Comment by Ben-G** [comment]
While I don't have time to look into this right away; it does seem to makes sense to be able to provide an interface that allows dispatching actions without knowing the generic type of a store.

@dodikk Would you mind sharing the details of your current workaround?

**Comment by dodikk** [comment]
>> @dodikk Would you mind sharing the details of your current workaround?

My workaround is using `var reduxStore: Store<PKAppState>` rather than `var reduxStore: StoreType`

I'd like to go with just `var reduxStore: StoreTypeStateless`

**Comment by dodikk** [comment]
>> it does seem to makes sense to be able to provide an interface that allows dispatching actions without knowing the generic type of a store.

I'll prepare a pull request these days
