### ISSUE TITLE
When to use/not use ReSwift?

### ISSUE THREAD

**Issue by ilandbt** [ReSwift/ReSwift#178]
Hi all,
I'm starting to work on a new project and looking around for new architecture ideas

Are there any use cases that you wouldn't recommend using ReSwift?

Is there a difference between state structure size? Is it possible to handle a huge state for a huge app?

Thanks

**Comment by Qata** [comment]
This is a very subjective question, but that being said I'll do my best to answer.

I don't think there are any cases where I wouldn't recommend using ReSwift, it's a library that seeks to make your application more robust and every application will benefit from its power if architected well.

I don't get what you mean by difference between state structure size, state structure is differentiated purely by its size.

It's entirely possible to handle a huge state! You should achieve this by nesting sub state structs of data sharing similar properties within the main state to avoid the main state being a huge mess of unrelated data.

**Comment by ilandbt** [comment]
Thanks, thats what i meant about different state sizes.
Nesting sub states answered my question.

Thanks again

**Comment by Qata** [comment]
Glad to help!
