### ISSUE TITLE
[Question] Direct call vs. `store.dispatch` for action creators

### ISSUE THREAD

**Issue by Ogel** [ReSwift/ReSwift#184]
I've just started reviewing ReSwift, and I'm in the process of trying to apply it to a new project.  I've been looking over the [GitHubBrowserExample](https://github.com/ReSwift/GitHubBrowserExample/tree/0327586b3e3b66362ba34c11a127de16e240a07f), and I have a question about when and why to use `store.dispatch` for certain situations.

The example project has an [action creator](https://github.com/ReSwift/GitHubBrowserExample/blob/fe99330a323400cfddc758a3c860de27912ece43/SwiftFlowGitHubBrowser/Actions/AuthenticationActions.swift#L13) that always returns nil itself, but it may fire some actions as side effects:
```
func authenticateUser(state: State, store: Store<State>) -> Action? {
    guard let config = state.authenticationState.oAuthConfig else { return nil }

    let url = config.authenticate()

    if let url = url {
        store.dispatch(SetOAuthURL(oAuthUrl: url))
        store.dispatch(SetRouteAction([loginRoute, oAuthRoute]))
    }

    return nil
}
```

The app doesn't fire this function directly, but instead uses `store.dispatch(authenticateUser)`.  Since this particular function always returns nil, is there any special reason to use `store.dispatch`?  Is it safe to call a function like this - one that may trigger actions in an asynchronous completion handler - directly?

The app I'm creating will make asynchronous calls to an API server, and I'm wondering if triggering these calls needs to go through the store for some reason.  Apologies if I missed this explanation in the docs somewhere - and thanks in advance!

**Comment by DivineDominion** [comment]
Thanks for pointing this out! The following is my personal opinion: the example code is misleading. I don't like it.

Action creators have a very special feature -- they get to know `(State, Store<State>)` as input. So this function makes use of the input without actually being a true action _creator_.

To me, this is cheating. I'd ask: "Why don't you write the app in a way that doesn't couple your event creation so high to ReSwift's ActionCreator? If you need the state, then get it by some other means."

As I said, that's just my personal take on this. I don't know if people repeatedly have to get access to the current `store.state` all of the time. I write service objects that e.g. subscribe to the `authenticationState` substate and act differently depending on the `oAuthConfig` attribute. But then again, maybe my OO is misleading :)

**Comment by DivineDominion** [comment]
Action creators were replaced by thunks https://github.com/ReSwift/ReSwift-Thunk/
