### ISSUE TITLE
State mutation instead of state copying

### ISSUE THREAD

**Issue by Dimillian** [ReSwift/ReSwift#198]
I need to discuss this, I'm not perfectly clear on how it works in Swift, 

If you look at the redux doc: http://redux.js.org/docs/basics/Reducers.html#handling-actions
Especially this passage:

> We don't mutate the state. We create a copy with Object.assign(). Object.assign(state, { visibilityFilter: action.filter }) is also wrong: it will mutate the first argument. You must supply an empty object as the first parameter. You can also enable the object spread operator proposal to write { ...state, ...newState } instead.

How does it works here with ReSwift? It seems like my Reducer handle action methods receive a state, mutate it and return it. Should I instead make a new state object and copy each of my previous inner state + the changes I want to make in the state I'll return?

**Comment by mjarvis** [comment]
@Dimillian ReSwift is intended to be used with value-typed state. Value types (IE structs / enums / base types like string, array, etc) are copy-on-write in swift, which means as soon as you mutate the variable, you're actually creating a copy.

If you use reference-typed objects (classes) in your state, you should make them immutable (if possible), and use manual copying in your reducers.

**Comment by Dimillian** [comment]
But for the moment ReSwift doesn't really check the state when emiting changes, is it? 
I mean by that that if I subscribe to a substate, newState will be called whenever the state change anywhere right?

**Comment by mjarvis** [comment]
Correct, there is no diffing of the state in the current release of ReSwift.

(Aside: I do have this in progress at https://github.com/ReSwift/ReSwift/pull/190 )

**Comment by Dimillian** [comment]
Yes I'm tracking that with big interest, this is actually one of the big reason why the state mutation is/should be forbidden. 

So is that correct ? Or should I first make a copy of my state arrays? 
I know the array could be the root of my state, but I plan to have other values around it.

swift
```
struct BooksState {
    var books: [Book] = []
}

func booksReducer(state: BooksState?, action: Action) -> BooksState {
    var state = state ?? BooksState()

    switch action {
    case let action as SetBook:
        if let book = action.response.object {
            state.books += Book(json: book)
        }
    }
   return state
}


func +=<T: Equatable> (lhs: inout [T], rhs: T) {
    if (!lhs.contains(rhs)) {
        lhs.append(rhs)
    } else if let index = lhs.index(of: rhs) {
        lhs[index] = rhs
    }
}


```

**Comment by mjarvis** [comment]
You're using a swift array there, which is a value type, so you're safe. You're "copying" the value when you do `var state = state`.

(For further detail, it actually does the copy later, only if the mutation occurs, as an optimization)

**Comment by Dimillian** [comment]
I forgotten in my previous code (adde now), Book is a class, not a struct, should it be a struct instead, in order to make a real copy and not a array of reference or is it not necessary? 

Thanks for your time!

**Comment by mjarvis** [comment]
Ah, I see. Ok, so, you're thinking about future conformance to equatable state for diffing?

Regarding the mutation, you seem to be initializing a new `Book()` from json each time, so there is no reference type mutation happening.

Problems would occur (once equatable state is in) if you were to do this in a reducer:
```swift
if let book = state.books.first {
    book.title = "mutation!" // BAD! mutating an object already in the state!
}
```

**Comment by Dimillian** [comment]
Busted, yeah I'm thinking future proof here 😎 I'm waiting for the Equatable merge (or implementing it myself for now). 

Ok I see, it's perfectly clear now, thanks!

**Comment by mjarvis** [comment]
Great -- I'll close this issue. And for reference, there is also a public Gitter channel ( https://gitter.im/ReSwift/public ) for more chat-style help.
