### ISSUE TITLE
subscribe<SelectedState, S: StoreSubscriber> require pass option closure

### ISSUE THREAD

**Issue by cpvincentsu** [ReSwift/ReSwift#199]
when i call the subscribe function, pass a closure; but get the error ```cannot convert value of type '(_) -> _' to '((_) -> _)?' ```

![image](https://cloud.githubusercontent.com/assets/20036028/22318920/58775cb2-e3b9-11e6-84a2-e39ac6950900.png)

pls see the image for your reference, thx

**Comment by mjarvis** [comment]
lowercase `AppState` -> `appState`, and make sure your `newState` function matches the tyope of `settingsState`, IE, `func newState(state: SettingsStateType) { ...`

**Comment by cpvincentsu** [comment]
thanks for your reply, the ```AppState``` is defined by me, it's the root state: 
```
struct AppState: StateType {
    var settingsState: SettingsState
}
```
i want the ```selectedState``` be the ```settingState```
```selector: ((State) -> SelectedState)?)```
but still, i'm not clear about how to call the closure to set ```selectedState```
![image](https://cloud.githubusercontent.com/assets/20036028/22341085/85140ccc-e42a-11e6-9a4a-2e9df25900fb.png)

**Comment by mjarvis** [comment]
```swift
import ReSwift

struct SettingsState {
    var setting: Bool = false
}

struct AppState: StateType {
    var settingsState: SettingsState
}

class Subscriber: StoreSubscriber {
    init(store: Store<AppState>) {
        store.subscribe(self) { appState in
            return appState.settingsState
        }
    }

    func newState(state: SettingsState) {
        print("State: \(state.setting)")
    }
}
```

**Comment by cpvincentsu** [comment]
great thx; i did set the AppState,  SettingsState like you;
but still get the type ```(_) -> _``` doesn't match ```((_) -> _)?``` error
![image](https://cloud.githubusercontent.com/assets/20036028/22342458/7260775a-e42f-11e6-9083-712fdefec1cb.png)

**Comment by mjarvis** [comment]
What about your `newState` function implementation?

**Comment by cpvincentsu** [comment]
Finally i got it, the ```newState``` function's parameter matters! thanks for your patience
