### ISSUE TITLE
Generate Code for Action Serialization

### ISSUE THREAD

**Issue by Ben-G** [ReSwift/ReSwift#2]
Currently a lot of boilerplate code is required in order to turn typed actions into serializable actions of type `Action`. Developers need to implement the `ActionConvertible` and `ActionType` protocols manually, e.g.:

``` swift
struct CreateContactFromEmail {
    static let type = "CreateContactFromEmail"
    let email: String

    init(_ email: String) {
        self.email = email
    }
}

extension CreateContactFromEmail: ActionConvertible, ActionType {

    init(_ action: Action) {
        self.email = action.payload!["email"] as! String
    }

    func toAction() -> Action {
        return Action(type: CreateContactFromEmail.type, payload: ["email": email])
    }
}
```

For most actions this could can and should be generated automatically. Using [SourceKitten](https://github.com/jpsim/SourceKitten) this should be _fairly_ straightforward.

**Comment by Ben-G** [comment]
This issue is now handled in this separate repo: https://github.com/Swift-Flow/Code-Generation

**Comment by DivineDominion** [comment]
So much has happened, I think we can safely close this :)
