### ISSUE TITLE
[Question] Unit Testing function types

### ISSUE THREAD

**Issue by ethanjdiamond** [ReSwift/ReSwift#201]
Hi ReSwift team, really like the library, and enjoy all the good work you're doing with it!

I was wondering why Middleware (and it appears Reducer now) is a function type, since it appears to not allow dependency injection. Let's say I have a middleware that makes network calls to a service of mine. Based on the action that comes in, it calls a MyService object that abstracts away the implementation details of the actual call. I'd like to be able to do something like this:

```
class ServiceMiddleware: Middleware {
    let myService: MyService
    init(myService: MyService) {
        self.myService = myService
    }

    func interceptAction(dispatch: DispatchFunction, getState: () -> StateType?) {
        // Something that captures an action, calls MyService, and then when it returns,
        // sends a new action with the data from MyService
    }
}
```

However, as a function type I'm not really sure how I would go about testing, since there would be no way to inject a fake MyService object into the function. TBH, I have no experience with functional programming, so maybe there's something I'm missing.

**Comment by mokagio** [comment]
Hi @ethanjdiamond 😄 . You are asking a great question!

There's a _functional_ way to overcome this apparent limitation. In Swift functions are first time citizens, which among other things means that you can have functions return other functions.

This means that you can write a function in which you inject your dependencies, and have it return a middleware or reducer. For example:

```swift
let analyticsMiddleware: (AnalyticsService) -> Middleware = { service in
    return { _, _ in
        return { next in
            return { action in
                switch action {
                case let action as SomeAction:
                    service.logEvent(action.someProperty)
                case let action as AnotherAction:
                    service.logOtherEvent(action.someOtherProperty)
                default:
                    break
                }

                return next(action)
            }
        }
    }
}
```

As for **why** those are better as functions than objects... I'm not the author of the library, and have no real experience with [Redux](http://redux.js.org/docs/introduction/) on which is inspired, but here's what I think.

The main advantage in having reducers and middleware being pure functions is that, when paired with value types, they enforce the immutability. This will prevent users from mutating their `StateType` without realizing it. Immutability is one of the big advantages of Redux, and one of the reasons it's such a safe architecture, and as such should be defended "at all costs". 🛡 .

**Comment by mokagio** [comment]
@ethanjdiamond I had a quick googling around, [this article](https://medium.freecodecamp.com/why-redux-needs-reducers-to-be-pure-functions-d438c58ae468#.p8atdj64e) might be interesting for you as well.

**Comment by ethanjdiamond** [comment]
@mokagio That article was super helpful. Thanks!
