### ISSUE TITLE
[improvement] Supporting NSError and NSData as a field of the StandardActionConvertible payload 

### ISSUE THREAD

**Issue by dodikk** [ReSwift/ReSwift#204]
The code below crashes inside the constructor of `StandardAction`.
As a workaround, I can put the `NSError components` (`domain`, `code` and `user info`) as separate payload entries. Still, it would be nice if payload could recognize `NSError` objects out of box.

```swift
public struct LoginErrorAction : StandardActionConvertible
{
    static let type = "LoginErrorAction"
    
    public var error: Error
    
    public init(withError localError: Error)
    {
        self.error = localError
    }
    
    public init(_ standardAction: StandardAction)
    {
        self.error = standardAction.payload!["error"] as! Error
    }
    
    public func toStandardAction() -> StandardAction
    {
        let payload: [String : AnyObject] =
        [
            "error" : self.error as NSError
        ]
        
        return StandardAction(
            type: LoginErrorAction.type,
            payload: payload,
            isTypedAction: true)
    }
}
```

**Comment by dodikk** [comment]
`NSData` values do not seem to work either.  A workaround that involves base16/base64 string encoding does not look nice.

You might suggest using filesystem cache and path URLs for BLOBs. 
Still, I guess, it would sometimes be useful to just conveniently have them in a state/action object.

**Comment by mjarvis** [comment]
@dodikk `StandardAction.payload` is documented as `JSON-compatible`. Objects such as NSData and NSError are not JSON encodable and thus cannot be supported in the payload.

I recommend breaking those objects down into a JSON-compatible dictionary, or, in the case of NSData, base64 encoding would be the best option.

**Comment by dodikk** [comment]
@mjarvis , thanks for your reply.

> StandardAction.payload is documented as JSON-compatible. 

Sorry, have not noticed that. 

Just curious, what are the reasons for not using `plist` or `NSCoding`?

**Comment by dodikk** [comment]
> I recommend breaking those objects down into a JSON-compatible dictionary, or, in the case of NSData, base64 encoding would be the best option.

I've already done so. But Still...

```
AS a ReSwift user, 
I'D LIKE TO see`NSError`, `NSData` or even `UIImage` support out of box 
SINCE they are used very frequently in the application's code. 
AND they are very likely to become a part of both app state and a part of state's increments (actions).
```

```
SO THAT every other developer would not writ his own serializer for such common objects.
```

**Comment by mjarvis** [comment]
> Just curious, what are the reasons for not using plist or NSCoding?

I don't know the answer to that, I'm fairly new to the project.

> Do you have any related debugging/reporting tools that are independent from Apple's platform?

[ReSwift-Recorder](https://github.com/ReSwift/ReSwift-Recorder) is the primary use case for StandardAction, as far as I know.

> SO THAT every other developer would not writ his own serializer for such common objects.

Those are common to you, but not necessarily common to others. Where do you stop? What about `NSDate`? or `NSSet`? The list goes on. Each user's needs are different.

These serializers are trivial to write, and need only be written once in a given project.

Including them would also require conditionals for different platforms (UIImage doesn't exist on macOS, do we serialize `NSImage` instead then?).

Alternatively, I could debate that you shouldn't be passing those actual objects & serializing them in the first place, but instead storing urls as to where those objects can be found on disk or web.

**Comment by dodikk** [comment]
>> Including them would also require conditionals for different platforms (UIImage doesn't exist on macOS, do we serialize NSImage instead then?).

That's a good point. I have not realized that ReSwift is used on Desktop as well. 
Then UIImage proposal does not make much sense.

**Comment by dodikk** [comment]
>> Alternatively, I could debate that you shouldn't be passing those actual objects & serializing them in the first place, but instead storing urls as to where those objects can be found on disk or web.

What you say does make sense (`SDWebImage` to the rescue) but I'm trying to say that `NSData` BLOBs sometimes make sense too. 

In my case this is a result from the image picker which is returned in the form of UIImage. It is supposed to be sent to the back end. I thought that having a single BLOB in a state/action should not hurt either the performance/user experience or the ideas behind the redux approach.

I might be mistaken since I'm new to this kind of an architecture.

**Comment by dodikk** [comment]
>> ReSwift-Recorder is the primary use case for StandardAction, as far as I know.

Sure. But it's also bound to Apple platform (iOS/OS X), isn't it? 

I was curious the **external** tools I might be missing. For example, 
* some script producing a sort of heatmap report
* some sort of integration with Instruments.app
* something similar to PonyDebugger or RealmBrowser

**Comment by dodikk** [comment]
@mjarvis , thank you for your time. I understand your position and I'm closing the ticket.

Still, I think, it would be nice (convenient for iOS/mac devs) if payload supported the same components as `plist` does. Would you consider a pull request with such changes if I made one? Or it's hopeless and I should not even bother?


The types I plan to preprocess for the payload are : 
* NSData (with base64 encoding)
* NSError (converted to dictionary)
* NSDate (as UTC timestamp in en_US_POSIX locale)

**Comment by mjarvis** [comment]
I'm not certain I'd consider that work inside the scope of the library, but its not up to me. cc @Ben-G
