### ISSUE TITLE
Clear Documentation and Version Information when using CocoaPods with Example App?

### ISSUE THREAD

**Issue by aaronksaunders** [ReSwift/ReSwift#209]
I have been trying for hours to download and run a sample application with ReSwift. 

Is there a simple example with the proper versions specified in the pod file and proper configuration in the Xcode project that actually runs?

From what I have observed, there are know issues with Swift, but for someone just trying to get started this has been a challenge

**Comment by Ben-G** [comment]
Hey!

I'm not sure which example project you tried out. I just tried the first one that's linked from this readme: https://github.com/ReSwift/CounterExample

Following the instructions it worked for me. Could you add some details on which projects you tried and how they failed?

Thanks!

**Comment by aaronksaunders** [comment]
@Ben-G sorry for not providing the information in the initial post.

I am trying to use cocopods... maybe that is the issue? "I have changed the title"

I am on version `Version 8.2.1 (8C1002)` of xcode

```
IMac27Quad:~ aaronksaunders$ xcrun swift -version
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
```

**Comment by aaronksaunders** [comment]
i got it to work by deleting the Carthage related files, removing the ReSwift.framework and then following the instructions for using the Podfile.

https://github.com/aaronksaunders/CounterExample-ReSwift-CocoaPods

Is there a specific risk in using cocoapods versus Carthage?
