### ISSUE TITLE
Syncing between devices?

### ISSUE THREAD

**Issue by fuzz** [ReSwift/ReSwift#212]
Hi,

We have a relatively complex productivity app and we are trying to solve two primary problems (with an eye on a third).
1. The architecture, such as it is, is largely a mess of years of legacy code
2. We need realtime device-to-device (for n devices) syncing
3. We will, in the near future, need to add sharing between users and team features—multiple users can own and modify a given item

We are looking at ReSwift and it seems to knock 1) out of the park, though I have some concerns about running out of memory for heavy users.

2) (and 3) which is 2) with n devices * n users) I am still trying to get my head around. I want to lean as much as possible on an off-the-shelf syncing system (Realm, Firebase or Ensembles most likely),  as we are a small team and syncing is hard. I have looked at https://github.com/ReSwift/ReSwift/issues/110 and treating the db like a web service makes sense. But then syncing that database looks like

Device A writes to a local Realm and then its store
Devices B and C receive the newly synced data to their local Realms via Realm Object Server
Any conflicts are resolved and changes are sent back to A, B and/or C local Realms as necessary

I observe the local Realms for changes. Upon receiving an incoming db change I…dispatch an Action? Not really asking for a specific solution here as much as wanting to know how hard this sounds to pull off, if anyone else is doing it and/or if it makes any sense to bother as it seems to sort of collapse into global mutable state :)

**Comment by DivineDominion** [comment]
I cannot say anything about the Realm part. But if the Realm syncing and sync version merging is resolved in your "Infrastructure" layer, you'll need to figure out how to design the sync result output port, so to speak.

If syncing results in a complete object graph, then you can pass this on to a service which assembles your app's model data from this. then `dispatch(ReplacingAllContents(convertedSyncResults))` or similar to show the updated data.

That'll do for a minimum viable product, but for live-syncing, you'll probably get deltas. Again, I have no clue how exactly. If we were a team and I'd be the App + ReSwift guy and you're the Realm/sync person, then I'd like to end up with an interface between our layers that tells me if an item should be `replace`d with new data, `insert`ed, or `remove`d. Maybe this gets more fine grained later. But for now, if you can provide me with these kinds of events, I'd write a wrapper for each that translates to `dispatch(InsertSomething(convertedInsertion))` and so on. In other words, the result of syncing will be mapped to actions that are similar to those a user will trigger manually.

**Comment by gistya** [comment]
The incoming data from other devices will get received  by your app in some listener class. Lets say this listener exists in the "Network Layer" of your app and runs in a background thread. 

From your app's perspective, this is just another form of input from outside itself. In that respect, it's really no different from user input that gets received by a viewController (on your "View Layer"). 

So, just like your user input (IBActions and UIGestures etc.) get transformed into Actions by the viewControllers in the View Layer, so also, you will want a syncController in the Network Layer that takes incoming messages from the other devices and generates Actions.

Such a sync Action could be something like, "merge the current app data with this chunk of data from Device #2". It would be up to your middleware or reducers or both to then figure out what to do about this situation. 

Now, the issues relating to syncing data between multiple devices are numerous and beyond the scope here, but using ReSwift should not block you from solving sync-related problems. 

Feel free to email me if you want to discuss the sync-related issues further, as I was just on a project where these matters took up much of our time. (I realize your comment is from 5 mo.s ago but let me know if you do.)

**Comment by DivineDominion** [comment]
As a collector of ReSwift related snippets and approaches, I'd love to hear more about your sync solution if you happen to have share-able info!

**Comment by mkayswork** [comment]
I am currently working exactly on this (Realm as a database + ReSwift + Sync). It might take a while until I am finished, but I can share my knowledge about this after I have finished it. Maybe I will also publish an article on medium about it.

If you want to share anything about this topic or have some hints I would be glad to stay in contact somehow :)
