### ISSUE TITLE
How ReSwiftInit case is intended to be used?

### ISSUE THREAD

**Issue by nikans** [ReSwift/ReSwift#216]
So in the docs there's something like this:

```
func authenticationReducer(state: AuthenticationState?, action: Action) -> AuthenticationState {
    var state = state ?? initialAuthenticationState()

    switch action {
    case _ as ReSwiftInit:
        break
   ...
    }

    return state
}
```

Though, state default initialization is conveniently moved to `initialAuthenticationState()` to unwrap `state`, so `ReSwiftInit` case does nothing.

1. How to use `ReSwiftInit` properly then? Having optional `state` is not really convenient, so it can be helpful if only you return newly initialized state, not copying and modifying the given.
2. More importantly, why do we even have optional state here?
3. What's the best practice to initialize default state? I see it's logical to put it in the state initializer, as a matter of fact.

```
struct AppState: StateType {
    var authState     = AuthState()
    var channelsState = ChannelsState()
    var locationState = LocationState()
}
```

and maybe use default initializers here:

```
struct ChannelsState: StateType {
    
    enum Channels {
        case loading(placeholderChannels:[Channel]?)
        case channels(channels:[Channel])
        case error(error: Swift.Error?, statusCode: Int?)
    }
    var channels: Channels = .channels(channels: [])
}
```

Thanks.

**Comment by DivineDominion** [comment]
I, too, use default state initializers and set up the "empty" state there. In fact, I call it thus:

```swift
struct AppState {
    static var empty: AppState {
        return AppState(authState: AuthState(),
            channelsState: ChannelsState(),
            locationState: LocationState())
    }

    var authState: AuthState
    var channelsState: ChannelsState
    var locationState: LocationState
}
```

Then in the main reducer, I ensure state isn't optional anymore and treat it thusly in all sub-state reducers:

```swift
func mainReducer(state: AppState?, action: Action) -> AppState {
    var state = state ?? .empty

    // delegate to sub reducers which use non-optional state

    return state
}
```

*Why* the state is optional and if this could be avoided, I don't know, really :) I try to get rid of the optionality as soon as possible.

I didn't find a good use case for hooking up something to the `ReSwiftInit` event either. It's implicit when state is `nil` at first. I guess one could do some side-effects like setup of daemons or whatever in a middleware that only reacts on `ReSwiftInit` passing through.
