### ISSUE TITLE
Should be able to call `newState` manually on subscribe?

### ISSUE THREAD

**Issue by ninjaprox** [ReSwift/ReSwift#219]
Should we have a API to subcribe without auto calling `newState(_:)`, for example `subscribe(_:delay:)`? I found it might be useful in some circumstances. My use case is:

- `object1` has many `object2`s // `object1` is subcribed to the store.
- Once `object2` newly  is added to `object1`, it's subscribed to the store // there is a loop in `object1` to do this.
- In `newState(_:)` of `object2`, it may change the store's state which calls `newState(_:)` of all subscribers.

And here is what happens if `subcribe(_:)` auto calls just added subscriber's `newState(_:)`, assuming we have `object2_1` and `object2_2` which are sibling and children of `object1`:

1. In the loop in `object1`'s `newState(_:)`, call `store.subscribe(object2_1)`. // `state#1`
2. In`object2_1`'s `newState(_:)`, change the store's state. // `state#1` -> `state#2`
3. In the loop in `object1`'s `newState(_:)`, call `store.subscribe(object2_2)` only as the `object2_1` is already added. // `state#2`
4. In `object2_2`'s `newState(_:)`, doesn't change the store's state. // `state#2`
5. ...

As a result `object2_2` didn't get `state#1` as it's supposed to, thinking of this as DFS with the state changing while it's going to lower level.

With `subscribe(_:delay:)`, we're able to change to BFS which solves the above problem, as the following:

1. In the loop in `object1`'s `newState(_:)`, call `store.subscribe(object2_1)`. // `state#1`
2. In the same loop in `object1`'s `newState(_:)`, call `store.subscribe(object2_2)`. // `state#1`
3. In the other loop in `object1`'s `newState(_:)`, call `object2_1._newState(state)`. // `state#1`
4. In that same loop in `object1`'s `newState(_:)`, call `object2_2._newState(state)`. // `state#1`
5. In`object2_1`'s `newState(_:)`, change the store's state. // `state#1` -> `state#2`
6. In `object1`'s `newState(_:)`, do nothing as both `object2_1` and `object2_2` are already added. // `state#2`
7. In`object2_1`'s `newState(_:)`, doesn't change the store's state. // `state#2`
8. In`object2_2`'s `newState(_:)`, doesn't change the store's state. // `state#2`
9. In`object2_2`'s `newState(_:)`, doesn't change the store's state. // `state#1`, the remaining from [4]
10. ...

By this way the sibling equally gets the same state at each level.

I'm also looking for better solutions, and so far the above proposal solves the problem.

**Comment by DivineDominion** [comment]
I think introducing a timed delay is the wrong approach. What you're after is not having ReSwift work synchronously: each `dispatch` and `subscribe` and `newState` is finished before the next step is taken.

You want to process `object2_1`...`object2_N` in a loop in a non-blocking way. Using `DispatchQueue.main.asyncAfter` could help to enqueue all subscriptions and returning from `object_1` earlier.

But you also experience the problem that some `object2_x` in the loop will, when its initial `newState` is called, dispatch a change to the store. So after `object2_x`, every new subscription will start with a state that's different from all the others. -- The thing is, a delayed subscription will not solve the problem. Because then `newState` is still called for every new subscription, only later.

When said `object2_x` modifies the state, all existing `object2_1`...`object2_x` subscriptions will receive the new state, too. So every subscriber works with the same state. There's no ultimate inconsistency.

So I wonder: what are you doing exactly that causes trouble?

---

A quick fix, btw, would be to introduce a `Bool`ean flag in your app state, like `object1DidFinish: Bool` that's only changed to `true` after all `object2_*` subscriptions have been set up. All `object2_*` subscribers will start with:

```swift
class Object2Type: StoreSubscriber {
    func newState(state: YourState) {
        guard state.object1DidFinish else { return }
        // dispatch changes
    }
}
```

Then the modifications will not happen during the initial post-subscription `newState` call, but only when the main object has finished its job.

**Comment by ninjaprox** [comment]
@DivineDominion: I agree with you above points. I also found it not an ultimate solution, but as a temporary solution.
What I'm doing exactly is, in fact, there's another layer called `object3_*` which is children of `object2_x`. `object3_x` also has `newState` as a store subscriber, but not subscribed to the store (the reason is the number of `object3_*` is far larger than of `object2_*`), i.e. `object2_x` will call `newState` of _some or none_ of `object3_*` according to its diff result (the diffing is performed in reducer).

Saying `object2_x` dispatches a change to the store, that means `object3_x` changes its state in `newState` (e.g. the initial state is placeholder size, then only in `newState`, it will be able to determine its real size and dispatch to the store), which changes the diff result in `object2_x` and make the state distribution to `object3_*` happen or not in the next iteration.

By the normal approach, whenever `object3_x` dispatches to the store, it holds back the current loop in `object2_x` and in `object1` until the loop in `store`'s `didSet` finishes. At that time, the diff result in `object2_x` has been changed, and as the result, `object2_x` doesn't have a chance to render its state based on its previous diff result.

I wonder if I'm using redux incorrectly. What should be a better solution for this?

**Comment by DivineDominion** [comment]
This sounds like a super weird case where objects subscribe and render and dispatch and set up more objects as subscribers.

Can you provide a concrete example? The object-x-y-z placeholders are too abstract for me to make a good decision.

Alternatively, a flow chart would be cool with what you want and what you get instead.

**Comment by ninjaprox** [comment]
@DivineDominion: I attach here the diagram of how it works, assuming that I'm using the delay approach. The normal approach is more complex to draw but the principle keeps the same.

![reswift issue](https://cloud.githubusercontent.com/assets/4948012/25752508/1ff9cc78-31eb-11e7-8a3c-1abec6f8ff84.jpg)

This is how the state looks like (just keep what matters):

```json
{
  "blocks": [
    {
      "id": 1,
      "diff": ".initial",
      "items": [
        {
          "id": 1,
          "size": 10
        },
        {
          "id": 2,
          "size": 10
        }
      ]
    },
    {
      "id": 2,
      "diff": ".initial",
      "items": [
        {
          "id": 1,
          "size": 10
        }
      ]
    }
  ]
}
```

In the nutshell, what I want is during the state distribution, i.e. the loop in `state`'s `didSet`, any changes to the state should be delayed until the iteration finishes.
I manage to do this by dispatching in the thread other than the main one and locking `state` in `didSet` which is run in the main thread. It's working well but there's a small delay from dispatching and rendering. Besides, I'm thinking to move `diff` from blocks to items which perhaps partially solve the problem. What do you think?

**Comment by DivineDominion** [comment]
Ha, great visualizations, thanks!

I wonder, conceptually, maybe the Blocks aren't really independent workers. Maybe a parent Block (or BlockCoordinator) should subscribe to the states and then delegate to all items in its array. This way you ensure that all blocks are called after another; the ReSwift store does not make any assumptions about order of subscriber notifications.

**Comment by ninjaprox** [comment]
@DivineDominion: Even though, it's still not guaranteed that the state won't be changed during delegation, which creates another delegation and hold on the current delegation.

**Comment by DivineDominion** [comment]
Ah, yes. Okay, but you could still make this less hacky:

1) use the container as store subscriber to manage the other objects
2) create all of these objects with the initial state as a parameter
3) subscribe all of them afterwards

This would ensure a clean and shared initial state in a fashion that's pretty easy to understand.

**Comment by ninjaprox** [comment]
@DivineDominion: By that way, it solves the problem at the initial load, but not if it happens onward. For example, after the initial load, everything is set, during a delegation, the item 1 dispatches the change to the store in its `newState`, which interrupts the current delegation and creates a new one, and it behaves as described in the diagram.

**Comment by DivineDominion** [comment]
I see. Two things come to mind:

1. Have you tried async action creators? I haven't used them in my apps, yet, so I cannot say if that'll help, but from what I _remember_ they _should_ (:)) dispatch only after the current dispatching is done, i.e. after all subscribers have received their updates
2. Don't subscribe each object on its own. If you want to process them in such an orchestrated way, use 1 subscriber that delegates down to the others. Also, don't dispatch from them directly, but use a delegate/callback to enqueue actions for dispatching by the container _after all sub-objects have finished._

**Comment by ninjaprox** [comment]
@DivineDominion: I also haven't tried async action creator in my case, I'll check it and let you know. If I'm correct, though, it just delays dispatching an action in async manner regarless the delegation finishes or not. The second suggestion sounds promising, I'll give it a try too. I think it's somehow similar to the locking approach I mentioned earlier, but with pros of not using a lock and handling in different threads.

**Comment by DivineDominion** [comment]
Re (1): Right, it adds executing the dispatch to the queue -- but you always operate on the same queue, so the sub-objects will append their updates until after their setup has finished. That should even work when each object is a subscriber, because ReSwift operates synchronously by default. That means every subscriber will get its state update, and when they dispatch an async action, that in turn means this action will not be processed immediately.

You could also achieve that by wrapping the `dispatch` call in `DispatchQueue.main.async`.

But recalling [Under the Radar ep 80](https://www.relay.fm/radar/80) about debugging, I don't think replacing your old sequential problem with a concurrency problem is a good idea. The problematic overhead is just too big.

So (2), the classic delegation approach, is way better.

**Comment by DivineDominion** [comment]
Cool! Glad I could aid in figuring this out :)

I'm collecting material for a book on ReSwift, so if you want to share demo code of before/after the change, I'd love to include your stuff in the text!

**Comment by ninjaprox** [comment]
@DivineDominion: Sure! How could I send the demo code?

**Comment by DivineDominion** [comment]
Whatever suits you best -- a GitHub demo repo, a Gist with just before/after, a blog post, or via email to: hi -at- christiantietze.de 

If you publish it somewhere on the web, I'll happily spread links to it earlier :)

**Comment by DivineDominion** [comment]
@ninjaprox by the way, I'm collecting material for a small practical guide (ebook). If you want me to discuss you case and refrrence your project, please get in touch via email

**Comment by DivineDominion** [comment]
For posterity, and for Googlers, here's a link to the OP's problem description and solution in a blog post: https://blog.vinhis.me/2017/08/12/ReSwift-a-weird-use-case.html
