### ISSUE TITLE
[Question] Swift 3 build error on latest master of ReSwift...

### ISSUE THREAD

**Issue by trips-app** [ReSwift/ReSwift#220]
**Hi, from New Zealand!**

First of all, I like the idea of this framework. I have been reading a fair amount about reactive programming lately, after deciding I needed a reactive state for my first iOS app.

Working in Swift 3.0.2, Xcode 8.2.1, and ReSwift 3.0.0, I am currently getting this error:
```swift
Cannot convert value of type 'AppReducer' to expected argument type '(Action, _?) -> _'
```

On this piece of code, where Xcode highlights **AppReducer()**:
```swift
struct App { static let store = Store<State>(reducer: AppReducer(), state: State()) }
```

I am also getting this error on my **AppReducer()** code:
```swift
Inheritance from non-protocol type '(Action, State?) -> State'
```
Which is probably related to **Reducer** becoming a *Function type*.

Where my **AppReducer()** code is:
```swift
struct AppReducer: Reducer<State> {
  func handle(action: Action, state: State?) -> State {
    var state = state ?? State()
    state = FileReducer.handle(action: action, state: state)
    state.drawers = DrawerReducer.handle(action: action, state: state.drawers)
    return state
  }
}
```
If I remove ```: Reducer<State>``` that error goes away, but I am also not sure if that will prevent the main *AppReducer* from working as intended.

Any help will be great, thanks.

**Comment by mjarvis** [comment]
Hi! the `Reducer` object has been changed recently from a protocol to a typealias, so your code will need to change to this:
```swift
 func appReducer(action: Action, state: State?) -> State {
    var state = state ?? State()
    state = FileReducer.handle(action: action, state: state)
    state.drawers = DrawerReducer.handle(action: action, state: state.drawers)
    return state
}
```

then you use it like this:
```swift
struct App { static let store = Store<State>(reducer: appReducer, state: State()) }
```

**Comment by mjarvis** [comment]
It looks like there are a number of places in the readme we need to update. Thank you!

**Comment by mjarvis** [comment]
https://github.com/ReSwift/ReSwift/pull/221

**Comment by trips-app** [comment]
Ah ha! I see now. Awesome. I'll change all my other Reducers to functions now.

Thanks! 👍
