### ISSUE TITLE
Does not compile with latest version of Swiftlint

### ISSUE THREAD

**Issue by nalexn** [ReSwift/ReSwift#235]
One of the build phases in the ReSwift is a custom script that launches Swiftlint check.
The problem is that with the latest Swiftlint version 0.17.0 they have introduced several new rules that have "error" severity and the code base apparently cannot pass the check and won't compile.

**Comment by mjarvis** [comment]
This should be fixed with https://github.com/ReSwift/ReSwift/pull/218, which should cause the swiftlint phase to only occur during development of the project, and pins it to a supported version.
Please update to latest master and try again. (A release will be out soon including this change)
