### ISSUE TITLE
[Question] Why Value Types (Struct) vs Reference (Class)?

### ISSUE THREAD

**Issue by garsdle** [ReSwift/ReSwift#236]
I am heavily considering trying out ReSwift because it looks really great and I really believe in the redux pattern. I was curious why ReSwift implements the AppState as a struct value type. Isn't it inefficient to have to update the entire state every time any sub state value changes? What will happen with really large/ rapidly changing states..

Anyways I appreciate any replies and all the work that goes into making this framework

Cheers!

**Comment by garsdle** [comment]
I'm also curious how listening to sub state changes works or if under the hood Reswift listens to changes of the entire state and filters out sub state changes.

**Comment by mjarvis** [comment]
> I was curious why ReSwift implements the AppState as a struct value type

ReSwift does not enforce that requirement. It only requires that the type conforms to `StateType` which is an empty protocol. You're welcome to make the app state a reference type, just be careful of the other implications of doing so.

> I'm also curious how listening to sub state changes works or if under the hood Reswift listens to changes of the entire state and filters out sub state changes.

The 4.0 release of ReSwift introduces state comparison functionality to skip equal state updates. If your app state / substate conforms to `Equatable`, you'll get this automatically. If not, you can implement `skipRepeats` after your substate selection to decide when or when not to call `newState`. (see https://github.com/ReSwift/ReSwift/releases/tag/4.0.0 )

**Comment by garsdle** [comment]
Awesome, thanks for the feedback!
