### ISSUE TITLE
Question on implementation details

### ISSUE THREAD

**Issue by alickbass** [ReSwift/ReSwift#238]
Hi guys! I have a somewhat strange question about the details of implementing Redux approach. Imagine, that you have a TabBar with 3 tabs. Every tab is the same UIViewController subclass. And the question is, how would you specify which view controller should subscribe to which part of state?

**Comment by danielmartinprieto** [comment]
Hi! For example, you could define an identifier for each instance of the subclass, and then use it to query the state of your app. Depending on the shape of each substate, you can abstract more or less the way you access them.

**Comment by alickbass** [comment]
That's pretty much way I thought it in my head 😃

**Comment by avdyushin** [comment]
Hey guys, can you show example?
