### ISSUE TITLE
Compliler and generic issues

### ISSUE THREAD

**Issue by Sully73** [ReSwift/ReSwift#244]
I'm trying out Reswift, but continue to have an issue when trying to create a reducer

```
struct AppReducer: Reducer {
        func handleAction(action: Action, state: AppState?) -> AppState {
        return AppState(tasks: [])
    }
}

```
The compiler is complaining 

> Reference to generic type 'Reducer' requires arguments in <...>

**Comment by DivineDominion** [comment]
Which ReSwift version are you using?

**Comment by Sully73** [comment]
@DivineDominion I'm using the latest 4.0

**Comment by rpassis** [comment]
The docs are out of date but have a look at the 4.0 release notes [here](https://github.com/ReSwift/ReSwift/releases/tag/4.0.0).

Basically the Reducer type was removed in favour of a function. This means you's write your reducer as:

```
func appReducer(action: Action, state: AppState?) -> AppState {
    ...
}

**Comment by Sully73** [comment]
@rpassis Great Thanks!
