### ISSUE TITLE
Reducer usage Swift 3.1 Xcode 8.3.2

### ISSUE THREAD

**Issue by nickpnmrv** [ReSwift/ReSwift#245]
Hi,

first of all thank you for introducing such an elegant pattern to iOS development!

I am following Getting Started Guide https://github.com/ReSwift/ReSwift#getting-started-guide an experiencing some problems implementing described architecture using Swift 3.1 and Xcode Version 8.3.2.

When I am creating my reducer

```
import ReSwift

struct AppReducer: Reducer {
    
    func handleAction(action: Action, state: AppState?){}
    
}
```

following error message is displayed:
_Reference to generic type ‘Reducer’ requires argument <…>_

Xcode is proposing to fix it as follows:
Fit-it insert “<Any>”

After adding my app state (struct i created implementing StateType) to reducer:

```
import ReSwift

struct AppReducer: Reducer<AppState> {
    
    func handleAction(action: Action, state: AppState?){}
    
}
```
I am getting following error:
_Inheritance from non-protocol type ‘(Action, AppState?)’ -> AppState_

Any idea what am I doing wrong? Are there some changes to Reducer Protocol I am missing?

Thank you in advance!

Best Regards,
Nick

**Comment by DivineDominion** [comment]
ReSwift v4 changed the procedure, see #244. Sorry for the confusion, but we were kinda lazy with the documentation :) I'll update the guide to reflect that. For a code sample, see the [release notes](https://github.com/ReSwift/ReSwift/releases/tag/4.0.0).

**Comment by DivineDominion** [comment]
Please have a look at #246 for an in-progress update to the guide, by the way 👍
