### ISSUE TITLE
add release checklist to repository

### ISSUE THREAD

**Issue by DivineDominion** [ReSwift/ReSwift#248]
Collecting things that come to mind (and which can be scripted in part):

- write release notes 
    - collect contributors per merged feature
- try to generate docs (how exactly?)

---

Feel free to edit this directly so we have a single point of reference.

Afterwards: 

- [x] add checklist to README or separate file
- [ ] write script to automate building the docs locally and pull list of PRs since last release

**Comment by DivineDominion** [comment]
checklist see #312

**Comment by mjarvis** [comment]
Don't the docs get automatically generated already? There is a CI script that gets run on master pulls: `.scripts/update-gh-pages`

**Comment by DivineDominion** [comment]
I don't know what I was thinking about in 2017 anymore. Maybe this was about easing local doc generation for proof-reading since #250 is referenced. I'm closing this anyway because 18 months without reaction indicates that this isn't super important :)
