### ISSUE TITLE
SkipRepeats and Equatable

### ISSUE THREAD

**Issue by MotiFer** [ReSwift/ReSwift#251]
I added unit test file using ReSwift 4.0.0 latest commit: dbc6b1aa08d58ec6e575ac14d13d42fc427e7295
```
//
//  OptionalTest.swift

import XCTest
import Foundation
import ReSwift

@testable import ReSwift

struct SomeState: StateType {
    var xyz = 5
}

struct TestAppState1: StateType {
    var someState = SomeState()
}

extension SomeState: Equatable {
    static func == (lhs: SomeState, rhs: SomeState) -> Bool {
        return lhs.xyz == rhs.xyz
    }
}

class TestFilteredSubscriber1: StoreSubscriber {
    func newState(state: SomeState) {
        print(state)
    }
}

struct TestOptionalReducer1 {
    func handleAction(action: Action, state: TestAppState1?) -> TestAppState1 {
        var state = state ?? TestAppState1()
        switch action {
        case let action as SetSomeAction:
            state.someState.xyz = action.zzz
            return state
        default:
            return state
        }
    }
}

struct SetSomeAction: Action {
    let zzz = 8
}


class OptionalTest: XCTestCase {

    func testSkipsStateUpdatesForEquatableSubstatesByDefault() {
        let reducer = TestOptionalReducer1()
        let state = TestAppState1()
        let store = Store(reducer: reducer.handleAction, state: state)
        let subscriber = TestFilteredSubscriber1()
        store.subscribe(subscriber) {
            $0.select { $0.someState }
        }
        XCTAssertEqual(store.state.someState.xyz, 5)
        store.dispatch(SetSomeAction())
        store.dispatch(SetSomeAction())
        XCTAssertEqual(store.state.someState.xyz, 8)
    }

}

```
When I run the test I get in console:
SomeState(xyz: 5)
SomeState(xyz: 8)

now when I change (notice the optional value in state)
```
class TestFilteredSubscriber1: StoreSubscriber {
    func newState(state: SomeState?) {
        print(state)
    }
}
```

I get:
Optional(ReSwift_macOSTests.SomeState(xyz: 5))
Optional(ReSwift_macOSTests.SomeState(xyz: 8))
Optional(ReSwift_macOSTests.SomeState(xyz: 8))

Can someone explain why I don't get into Equatable function for the state?
- Need to fix the test to fail going twice on same value for Equatable

**Comment by MotiFer** [comment]
@DivineDominion Yes it does work.
Its easy to forget that `Optional` does not conform to `Equatable`.
This can happen a lot when using states , I would like to have a general solution.
Any one have any idea how to approach this?

**Comment by mjarvis** [comment]
@MotiFer you could add another `select` function to `Subscription`, such as this (untested)

```swift
func select<Substate: Optional>(_ selector: @escaping (State) -> Substate) -> Subscription<Substate> where Substate.Wrapped: Equatable {
    return self._select(selector).skipRepeats(==)
}
```

**Comment by DivineDominion** [comment]
@mjarvis wouldn't that be a good candidate for a PR to ReSwift, too? 🤔

**Comment by mjarvis** [comment]
@DivineDominion Yes, it could be if it works. Though it sort of leaves the question of how far one goes with boxed objects, vs waiting for swift to support pass-through equitability conformance.

**Comment by DivineDominion** [comment]
@mjarvis I am tinkering with extensions for ReSwift, too, and I find the default visibility to limit a lot -- if you don't want to maintain your own fork.

I'd suggest making more stuff public for the sake of extensibility:

- `Subscription._select` itself (meh), or 
- `Subscription.observe` so people can write their own transformers. (👍)

Thoughts?

**Comment by mjarvis** [comment]
Re: The original issue here, there is an accepted proposal in swift ( https://github.com/apple/swift-evolution/blob/master/proposals/0143-conditional-conformances.md ) that will make things like `Optional` conform to `Equatable` when appropriate, which resolves this issue.

I don't think its worthwhile for us to explore a solution when Swift itself will be resolving the problem. I vote to close this issue, if anyone else agrees please go ahead and close.
