### ISSUE TITLE
[Question] How to deal with scoped (or short lived) state?

### ISSUE THREAD

**Issue by grimrecka** [ReSwift/ReSwift#257]
Say I have a contacts app. Storing the entire array of contacts and their detail in state makes sense as multiple things would want to subscribe to updates for this. The contact list view controller needs this to display a collection view of all the contacts, and the contact details view controller would need access to this show the info for a single contact.

But some state only makes sense in relation to a specific view. A sign in view controller would have state for the currently entered email and password, and whether or not to show a activity indicator. But nowhere else in the app cares about this state. No other screen needs to know when this state changes or even that it exists in the first place.

Ignoring the last two issues, you could have an optional `SignInState` value in the root state struct, that is initially nil, gets set with a default by a reducer when the sign in view is created and cleared when it is closed. But how does this work with view controllers that can nest themselves infinitely. Suppose the contact details view controller has its own state, e.g. some views have expanded/collapsed state, has a list with a contacts family members who you can tap on to open another contacts details view controller. This view controller would have it's own state as well. Using an optional `ContactDetailsState` in the root state object wouldn't be possible in this situation because both would trying using it to.

So where is a good place to store this kind of state?

**Comment by danielmartinprieto** [comment]
Hi! The original Redux's docs have FAQ section where they cover most of these concerns in a conceptual way. I think it's worth to take a look.

http://redux.js.org/docs/faq/OrganizingState.html

**Comment by DivineDominion** [comment]
@grimrecka additionally, if you need to support multiple instances of a view controller at different routes, I'd look at the Router library -- there, you can assign a `ContactDetailState` to different routes by utilizing the routable state dictionary. You can also reuse a single view controller instance and display different data. You just have to make the routes reconfigure the view controller they manage.

For non-nestable routes, I experimented with a custom approach; cannot recommend pasting the code in, but maybe the Module/Route setup makes sense to you: https://github.com/DivineDominion/ReSwift-CustomRouting/blob/master/ReSwift-CustomRouting/Modules/Detail/DetailModule.swift

**Comment by DivineDominion** [comment]
This reminds me of @dagio, maybe he has some practical advice to offer *ping*

**Comment by dagio** [comment]
[Navigation.zip](https://github.com/ReSwift/ReSwift/files/1067382/Navigation.zip)

I attached here an archive that contains the list of addition we made but not yet published regarding ReSwift and navigation. Have a look to `RouteStateRestoration.swift`. It originally come from @Ben-G

**Comment by grimrecka** [comment]
Thanks everyone! These suggestions look promising.

**Comment by DivineDominion** [comment]
Cool, I'll close this then.
