### ISSUE TITLE
[Question] Threading ? 

### ISSUE THREAD

**Issue by Dimillian** [ReSwift/ReSwift#258]
I'm noticing an increasing "lag" when a new state is dispatched, because I have a more and more complex state implementing Equatable and using skipRepeat. Is there a way to make my state comparison on a background queue? Would making a custom Subscription a good place?

**Comment by Dimillian** [comment]
Okay silly me. I can just subscribe in a custom queue and my subscription will be called in that queue. Perfect!

**Comment by DivineDominion** [comment]
This is an interesting bottleneck nevertheless. `skipRepeats` wouldn't work well out of the box for larger collections. That's why I compare in my subscriber using not `==` but a "similar enough" operator instead whenever applicable, kind of like a shallow comparison. But you'll have to write that for every type that can have large objects.

For another part of the same app, I added versioning (an incrementing number) to user-initiated requests to discard outdated responses. I wonder if versioning would be a useful for ReSwift states in general through an extension maybe.

**Comment by Dimillian** [comment]
I'll add some more do the discussion after my research: 

So about Equatable, I implement it everywhere it make sense, and for collections I have some very specific implementation case by case, sometimes it make sense to do a deep comparaison on every objects, sometime I need it to be fast, so just comparing ids/string is ok. The downside is that my states and objects are very bloated and it's hard to see what equatable are really doing. So I use the == of Equatable because it's convenient, but it's some case it's more about being similar enough. 

I also have custom operator for merging operations in my reducer, but that's another story. 

About threading, I'm doing everything on a serial high priority background queue now, in short, it looks like that:

```
let FLUX_QUEUE = DispatchQueue(label: "xxx.appName.xxx.store.queue")

extension DispatchQueue {
    public class func flux() -> DispatchQueue {
        return FLUX_QUEUE
    }
}

```

and

```
extension Store {

    open func dispatchQueue(_ action: Action) {
        DispatchQueue.flux().async {
            self.dispatchFunction(action)
        }
    }
}

```

So I use dispatchQueue whenever I would have called a store.dispatch. 

The only downside is that I don't see how to shortcut StoreSubscriber to be called on the main thread, I guess I have so shortcut subscriber first and register my custom class etc... So for now I need to remember to use the main queue in all my new state function call. 

Do you think of a better way of doing that @DivineDominion ?

**Comment by Dimillian** [comment]
@DivineDominion about versionning, you have exactly the same problem as me for my live search! 
I store a state that is define by a [queryString: [results]], so whenever you would go back to a query that is already in the state, the newState would never be called with the skipRepeat implementation. I ended up storing a timestamp and a lastSearch in my searchState which is updated every time a search is fired, so I'm sure the subscriber is called so I can refresh my UI. 

I could manually pull my results from my store from my viewController but it kinda breaks my workflow.

**Comment by DivineDominion** [comment]
@Dimillian since people type fast in my app and results are supposed to provide instant filtering of in-memory results, I use an incrementing integer instead of a timestamp just for good measure, but yeah, this is like server--client architecture in a single app. In other words, cumbersome :)

Have a look at `ReSwift.Subscription`. Maybe it makes more sense to provide an extension first where you have a custom transformation (like `select` or `skipRepeats`) that wraps passing the result back in your `DispatchQueue`. If that works, and if writing this transformation everywhere gets on your nerves, you could pull the combination into a `subscribeOnXYZQueue` method.

This sounds much like RxSwift `subscribeOn`, by the way. And I guess this could be a useful extension to the core library. At least it can make sense to discuss this some more!

**Comment by Dimillian** [comment]
@DivineDominion Well I debounce it, so it's not triggered at every keystroke; but still fairly often. Server query -> reduce results ||&& local search -> dispatch state change -> etc...  I get pretty good performance and a nice flow now. 

I may get something wrong, but subscribing on a specific queue and dispatching action on a specific queue is something different right? I can subscribe on any queue/main thread, but as long as I trigger my dispatch actions in a specific queue, the subscriber will be called on that queue right and not on the subscriber one, right?

**Comment by DivineDominion** [comment]
@Dimillian  Oh you're right, ReSwift doesn't schedule anything special. It looks like the subscriber will be called from the same queue where the action is dispatched. Doing this from anywhere is not encouraged, so I assume you dispatch from the main queue. 

Let's hope I get the rest of this right :)

Now you want to process the equality check (`Subscription` transformation) on a different queue. That would be possible if you wrote a transformation like the built-in `select`:

    public func select<Substate>(
        _ selector: @escaping (State) -> Substate
        ) -> Subscription<Substate>
    {
        return Subscription<Substate> { sink in
            self.observe { oldState, newState in
                sink(oldState.map(selector) ?? nil, newState.map(selector) ?? nil)
            }
        }
    }

Sadly, writing transformations like this is not possible from the client app's side at the moment. I'll try to incorporate this in #263 but for now you'd have to write this in a ReSwift fork:

```swift
// Untested
extension Subscription {
    public func onQueue(_ queue: DispatchQueue) -> Subscription<State> {
        return Subscription<Substate> { sink in
            self.observe { oldState, newState in
                queue.async {
                    sink(oldState.map(selector) ?? nil, newState.map(selector) ?? nil)
                }
            }
        }
    }
}
```

Then call it like this:

```swift
store.subscribe(foo) { $0.onQueue(.flux()).skipRepeats(==) }
```

**Comment by Dimillian** [comment]
Yeah it might be better when I'll be able to too that hehe. But as of now, I'm doing everything on my flux queue, and get back to the main thread on the new state callback. It works, just a bit more code :)

**Comment by MichaelGuoXY** [comment]
I tried with dispatching actions on my custom serial queue, but there are race conditions when I dispatch 2 actions at almost the same time, both are trying to modifying the same state value. So I guess I am supposed to dispatch actions only from the main thread?

**Comment by mjarvis** [comment]
@MichaelGuoXY All actions must be dispatched in a serial manner. If you are experiencing a race condition then the actions are not being dispatched serially. Perhaps your queue is setup incorrectly. If you believe it to be setup correctly, please create a separate github issue including a small sample project for us to replicate the issue with.

**Comment by MichaelGuoXY** [comment]
> @MichaelGuoXY All actions must be dispatched in a serial manner. If you are experiencing a race condition then the actions are not being dispatched serially. Perhaps your queue is setup incorrectly. If you believe it to be setup correctly, please create a separate github issue including a small sample project for us to replicate the issue with.

I've created a new issue here https://github.com/ReSwift/ReSwift/issues/443 please take a look, thanks
