### ISSUE TITLE
How to use ReSwift together with Eureka?

### ISSUE THREAD

**Issue by marbetschar** [ReSwift/ReSwift#260]
I'm currently evaluating some new architectural grounds and I'm wondering how you would use [Eureka](https://github.com/xmartlabs/Eureka) best together with ReSwift? Maybe even together with RxSwift?

Has anybody already experience in using Eureka together with ReSwift?

**Comment by DivineDominion** [comment]
I haven't used it, yet. But I don't see anything special. You keep the view state isolated (i.e. inside the active form) until the user finishes (hits the "Done" nav button, for example). Then you fetch the row values, create a form model, and then you can dispatch an action.

Getting the values seems to be straightforward:
https://github.com/xmartlabs/Eureka#getting-row-values

**Comment by DivineDominion** [comment]
Closing this for now. Feel free to reopen if you have any question unanswered!
