### ISSUE TITLE
[BUG] Callback not triggered when setting nil to an optional sub-state.

### ISSUE THREAD

**Issue by lkzhao** [ReSwift/ReSwift#265]
When subscribing to an optional sub-state using `.select`. the callback is not triggered when the sub-state changes to `nil`

Example:
```swift
struct AppState: StateType {
    var name: String?
}
func reducer(action: Action, state: AppState?) -> AppState {
    var state = state ?? AppState()
    switch action {
    case let action as ChangeName:
        state.name = action.name
    default:
        break
    }
    return state
}
```
Subscribe like this:
```swift
class Test: StoreSubscriber {
    init() {
        mainStore.subscribe(self) {
            $0.select {
                $0.name
            }
        }
    }
    func newState(state: String?) {
        print("new name:", state)
    }
}
```
```swift
// this works.
mainStore.dispatch(ChangeName(name: "Luke"))
// the callback is heard

// this doesn't. the callback is not heard by the subscriber. Even though the state has changed.
mainStore.dispatch(ChangeName(name: nil))
```

Here is a playground that demostrate this bug:
[TestDrive-ReSwift.xcworkspace.zip](https://github.com/ReSwift/ReSwift/files/1103321/TestDrive-ReSwift.xcworkspace.zip)

**Comment by lkzhao** [comment]
I have identified the problem and fixed it on my fork. But it isn't an ideal fix. You can take a look here if you want to dive in deeper.
https://github.com/lkzhao/ReSwift/commit/8407b5c1d094d40ccb39010497c4f8873d36b0a2

The problem exist in `ReSwift/CoreTypes/StoreSubscriber.swift`
```swift
public func _newState(state: Any) {
  if let typedState = state as? StoreSubscriberStateType {
    // the line above filters out nil, even when StoreSubscriberStateType is an optional type
  }
}
```

**Comment by Ben-G** [comment]
@lkzhao Thanks a lot for reporting this! Will think about how to fix this best.

**Comment by Ben-G** [comment]
Hey @lkzhao, see #266 for a potential fix for this issue!
