### ISSUE TITLE
You never give an example of how to set payload in reducer

### ISSUE THREAD

**Issue by patientplatypus** [ReSwift/ReSwift#268]
As someone who is knew to redux like state management, this is almost a complete deal breaker. You have the following defined as an action:

```
struct StandardAction: Action {
    // identifies the action
    let type: String
    // provides information that is relevant to processing this action
    // e.g. details about which post should be favorited
    let payload: [String : AnyObject]?
    // this flag is used for serialization when working with ReSwift Recorder
    let isTypedAction: Bool
}
```

Neat! So I want to take a string, send a payload that I will set as the new string. So I would set it in the action, and then in the payload I would....

```
func authenticationReducer(state: AuthenticationState?, action: Action) -> AuthenticationState {
    var state = state ?? initialAuthenticationState()

    switch action {
    case _ as ReSwiftInit:
        break
    case let action as SetOAuthURL:
        state.oAuthURL = action.oAuthUrl
    case let action as UpdateLoggedInState:
        state.loggedInState = action.loggedInState
    default:
        break
    }

    return state
}
```

wtf is this? Is action.oAuthUrl the payload? Is there even a payload even here? Who knows! Syntax is inconsistent throughout (every section is a different example from scratch hurray!) and variables are not the same. Complete dumpster fire.

**Comment by mjarvis** [comment]
I suggest you take a look at https://github.com/ReSwift/ReSwift/blob/8fb16bca793850f002fe1b43926e37370aad65e1/Docs/Getting%20Started%20Guide.md#minimal-working-example which is in that guide and provides a minimal working example of all the parts of ReSwift.

The example you've copied here shows a reducer that handles a few different action types such as `SetOAuthURL`, which would be defined as follows:
```swift
struct SetOAuthURL: Action {
    let oAuthUrl: URL
}
```

`StandardAction` is the action type to be used if you need to support recording / rewinding of actions via https://github.com/ReSwift/ReSwift-Recorder

**Comment by DivineDominion** [comment]
Good point that every example is different, @patientplatypus. Never thought about that. Now that you _do_ come from a Redux background, can you help me sort this out and explain what you expect?

**Comment by patientplatypus** [comment]
Ok. Sorry, for the static. I'm under a lot of stress lately (still no excuse).

You should update the docs with this example rather than the "counter" one. That example is not a fully functional battlestation because 1) it doesn't pass payloads which is what most people starting out want and 2) it doesn't explain this for retarded giraffes.

# Here is the example that is the most trivial for n00bs.

**Step 1.** _Install using cocoa pods_

Install using cocoa pods or one of the other installation methods already mentioned.

**Step 2.** _Modify AppDelegate.swift file to reference what will go in the State.swift file (which you will make)_

Add these lines at the top before `@UIApplicationMain` tag and after `import UIKit`

```
import ReSwift

let mainStore = Store<AppState>(
    reducer: mainReducer,
    state: nil
)
```

**Step 3.** _You now need to make a new file State.swift that you just referenced_

```
import Foundation
import ReSwift

struct AppState: StateType {
       var MyName: String = ""
}
```

**Step 4.** _Inside your ViewController.swift file send the action to ReSwift dispatch._

Select a ViewController that references a storyboard in your ViewController.swift file where you will be using to make this example work. Make sure that the storyboard class in your main.storyboard matches the class of your ViewController class that you will be referencing in your ViewController.swift file. You can set this by clicking on the yellow circle at the top left of the storyboard gui in main.storyboard and in **interface builder** going to the **identity inspector** tab and naming the custom class.

Make a button by control dragging from your storyboard and selecting action. Name this button `MyButtonThatSetsName`. Set a payload that you want to send (here I have set "platypus"). You can later call a text variable from elsewhere in your component, but for now keep this trivial.

```
 @IBAction func MyButtonThatSetsName(_ sender: UITextField) {
        mainStore.dispatch(MyNameAction(payload: "platypus"));
    }
```

**Step 5.** _Since we are dispatching this action we now need to make the actions.swift file where this will be dispatched **to**_

Make a new file named Actions.swift.

Inside the file put the following.

```
import ReSwift

struct MyNameAction: Action {
    let payload: String
}
```

**Step 6.** _Now that we have made the actions, we need to make a reducer file and set the new state._

Make a new file named Reducers.Swift

Put the following inside it.

```
import ReSwift

func mainReducer(action: Action, state: AppState?) -> AppState {
    var state = state ?? AppState()
    
    switch action {
    case let action as MyNameAction:
        state.MyName = action.payload
    default:
        break
    }

    return state
}
```

**Step 7.** _Now, if everything was done correctly, you should be able to output the result in our ViewController.swift file_

Control drag a uilabel onto your main.storyboard (from the **object library** in the lower right hand corner of the **interface builder**). Then click on the new uilabel and control drag onto your ViewController class. Name it **returnedName**. It should look like this:

`@IBOutlet weak var returnedName: UILabel!`

The default text for this label will be "label". You can go into interface builder and change this if you like, but you do not have to.

Also make another action button as we did in step one, so that when there is a button press we can set the label text from the action store. Call it **setName**. The default button will be "button", you can go into interface builder and change it if you like, but again, you don't have to.

It should look like this:

    ```
@IBAction func setName(_ sender: Any) {
    
    }
```

Now we want it so that when we press this button the name that we have will populate the label. Paste the following code inside your new button action, so it looks like this.

```
   @IBAction func setName(_ sender: Any) {
        returnedName = "\(mainStore.state.MyName)"
    }
```

**Step 8.** _Yay we're done! Now what? Next Steps._

If everything was done correctly, you should see that your new label will populate with the hardcoded name you have entered at the beginning. Now, if you would like, you can as a next step take user input from a text field to populate the username. A step after that is to have information populate the name field in one storyboard/viewcontroller and have it retrieved in another. Remember one of the great things about uni-directional data flow is that you don't have to push state between view controllers, you can push and retrieve from state. Happy hunting.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

So.....that's the kind of thing, that would have saved me a few hours of frustration. I don't know if everything in here is 100% correct, but it might be useful for the little people (i.e. me).

**Comment by DivineDominion** [comment]
Amazing effort, @patientplatypus! Thanks!

**Comment by DivineDominion** [comment]
@patientplatypus I was just reading the example again to plan a documentation change. What struck  me is the term "payload" for the text property. In your initial comment, it seemed you recognize this term put meaning into it -- yet you picked this instead of a more favorable, because less generic, property like `name`. I don't intend to point at you and tell you your code is bad or anything. Instead, I'd like to ask you to define or describe what "payload" means (or meant) to you. The [Redux.js docs](http://redux.js.org/docs/basics/Actions.html) simply use it as part of the definition for `Action`. I'd like to help Redux-savvy people map known concepts to ReSwift, and this might be helpful and I'm aware that I could be missing something important.

Since #270, `StandardAction` is not a part of the core `ReSwift` anymore. So at least parts of the initial source of confusion is gone, by the way :)
