### ISSUE TITLE
Should `StandardAction` be moved to ReSwift-Recorder?

### ISSUE THREAD

**Issue by mjarvis** [ReSwift/ReSwift#269]
It seems like the existence of `StandardAction` and `StandardActionConvertible` is somewhat confusing to new users, and does not really have a direct use within the base ReSwift library.

Without a compelling reason to leave it, I suggest we move it to `ReSwift-Recorder`.

**Comment by Ben-G** [comment]
👍  Sounds like a good idea to me!

**Comment by DivineDominion** [comment]
I agree!
