### ISSUE TITLE
Make compiler complain if store is mutated elsewhere then inside reducer

### ISSUE THREAD

**Issue by hlineholm** [ReSwift/ReSwift#279]
I've just started using ReSwift in one of my applications and was implementing my first reducer when I realised that it is possible to mutate state properties from anywhere in my code: 
```
var store = Store<State>(reducer: appReducer, state: State())
store.state.property = newProperty
```
Defining the property as immutable will cause _Cannot assign to property: 'newProperty' is a let constant_ compiler error:
```
let store = Store<State>(reducer: appReducer, state: State())
store.state.property = newProperty 
```
I guess it is possible to initialise a mutable state from the immutable one when inside a reducer but I was wondering if you guys have any thought on this subject already? How would you make the compiler complain when state is mutated elsewhere then from inside a reducer?

**Comment by mjarvis** [comment]
@hlineholm This issue is caused by the State property being `public var state` in `Store.swift:L26`. There have been other questions about re-adding the `private(set)` designation to that property https://github.com/ReSwift/ReSwift/issues/264 but no discussions / follow-up has been made.

**Comment by hlineholm** [comment]
I see. Fixing #264 will fix this issue as well. Thanks for the reference @mjarvis.
