### ISSUE TITLE
ReSwift port to Kotlin

### ISSUE THREAD

**Issue by ambientlight** [ReSwift/ReSwift#281]
Hi guys,

I have implemented the port of ReSwift to Kotlin. [GeoThings\ReKotlin](https://github.com/GeoThings/ReKotlin)

Obviously, our goal here is to have Kotlin port corresponding to ReSwift as closely as possible, so that everyone implementing both iOS and android apps have as smooth sail as possible.  

Few differences exist though:

### Dereferencing subscribers will not result in subscription removed

In ReSwift when you dereference the subscriber or it goes out of the scope, you won't receive new state updates. 

```swift
var subscriber: TestSubscriber? = TestSubscriber()
store.subscribe(subscriber!)
subscriber = nil
```

However in ReKotlin you need make sure you have unsubscribed explicitly.

```kotlin
val subscriber = TestSubscriber()
store.subscribe(subscriber)
store.unsubscribe(subscriber)
```

Because of this thing, I had to ignore `testStrongCapture()` and `testRemoveSubscribers()` in unit tests.

### Equatability and skipRepeats

When subscribing without substate selection like `store.subscribe(someSubscriber)` in swift you need to have your state implementing Equatable in order to skipRepeats being applied automatically.

```swift
public struct State: StateType {
    public let mapState: MapState
    public let appState: AppState
}

extension State: Equatable {
    public static func ==(lhs: State, rhs: State) -> Bool {
        //...
    }
}

```

However in Kotlin(JVM) every object implements `equals()`, so that skipRepeats will be applied automatically when you `store.subscribe(someSubscriber)`, with Kotlin [Structural Equality](https://kotlinlang.org/docs/reference/equality.html#structural-equality) check used.

In terms of implementation I tried to keep as close as possible to original source. The only notable difference is the fact that kotlin supports parametrized interface types that avoid the need of type erasure.

__Please take a look and let me know your thoughts! Any suggestions or contribution is highly appreciated.__

There are more work on the roadmap. Over the next few weeks I hope to get done with:
- [ ] port all docs
- [ ] ReSwift Router port
- [ ] ReSwift Recorder port
- [ ] Advanced examples.

**Comment by Dimillian** [comment]
Wow! Will take a look!

**Comment by DivineDominion** [comment]
That's an interesting and educational spin! Great!

**Comment by kmmraj** [comment]
Wow, this is great, please list the pending works in roadmap, happy to contribute

**Comment by hlineholm** [comment]
@Ben-G @mjarvis @DivineDominion @ambientlight can we move [GeoThings/ReKotlin](https://github.com/GeoThings/ReKotlin) to this organisation? As its purpose is to create a port of ReSwift to Kotlin, I think it belongs here. Me and my team are considering using a combination of ReSwift and ReKotlin in near future apps and it's much easier to motivate others on my team if the ReSwift orginazation takes ReKotlin under its wings.

**Comment by ambientlight** [comment]
@hlineholm it has been moved into it's own organization - https://github.com/ReKotlin 

However, I haven't yet added any a notice in https://github.com/GeoThings/ReKotlin. (Will do that asap)

**Comment by hlineholm** [comment]
@ambientlight great!

**Comment by mjarvis** [comment]
@hlineholm I understand why one would want ReKotlin to live under the ReSwift banner, but it would also create an assumption that the ReSwift team would be involved in its maintenance & updates, which we are unable to do (even giving ReSwift the time it needs is difficult).
I think I'd reconsider my opinion on this matter if/when ReKotlin grows its own community & maintainers, and is able to keep pace with ReSwift changes. At that time I think bringing them together might be beneficial.

**Comment by mjarvis** [comment]
@ambientlight It may be too late now, but Github does have "Transfer repository" support, which would cause the initial repo to redirect.
I think now you'd need to delete the new repository, then go to the old one, Settings -> Options, then scroll all the way to the danger zone.

**Comment by kmmraj** [comment]
@hlineholm We have the port of ReKotlin-Router [here](https://github.com/ReKotlin/rekotlin-router), it is in preview stage and we are using it already in some apps. Feel free to contribute.

**Comment by ambientlight** [comment]
> It may be too late now, but Github does have "Transfer repository" support, which would cause the initial repo to redirect.

@mjarvis our company's decision was to keep the original repository under our organization, though my original through was the same as you suggested.

another thing is that I am no longer developing/maintaining our internal project that ReKotlin was originally written for though I hope to improve on contribution when I'll get some more spare time in several month from now

**Comment by DivineDominion** [comment]
There was neither progress on ReKotlin nor on this issue, so I'm closing it for now.
