### ISSUE TITLE
How to subscribe to several substates?

### ISSUE THREAD

**Issue by nikans** [ReSwift/ReSwift#284]
```
store.subscribe(self) {
    $0.select { ($0.monogenicListState, $0.monogenicListSearchState) }
}
```

> _Type of expression is ambiguous without more context_

And

```
func newState(state: (MonogenicListState, MonogenicListSearchState)) {
    ...
}
```

**Comment by DivineDominion** [comment]
Does the error change to something more specific when you add the closure paramter types?

**Comment by nikans** [comment]
no, these 2 fragments are both there

**Comment by nikans** [comment]
meh, I've been having these problems because I've inherited from another store subscriber class and obviously the compiler couldn't quite understand, what do I want.
