### ISSUE TITLE
SubState and Equatable????

### ISSUE THREAD

**Issue by luongnhatlam** [ReSwift/ReSwift#286]
#283 Hi all, please help me how to compare the SubState conform Equatable protocol. This is my struct SubState:

> struct EventHomeState:StateType {
    var events:[Event] = []
    var loadingType:LoadingType = LoadingType.none
}
>
I want my `subcriber` only receive `newState` method when `events` array have changed but I don't know what is `EventHomeState` will compare with `==` operator??

**Comment by DivineDominion** [comment]
Looks similar to your old problem (#283):

```swift
// assuming
struct AppState: StateType {
    var eventHomeState: EventHomeState
}

// and
extension Event: Equatable { }

store.subscribe {
    $0.select { appState in
        appState.eventHomeState
    }.skipRepeats { lhs, rhs in
        lhs.events == rhs.events
    }
}
```

**Comment by luongnhatlam** [comment]
Yes, the problem still not fix. I will try this way. @DivineDominion thank you very much

**Comment by DivineDominion** [comment]
@luongnhatlam how did this turn out?

**Comment by luongnhatlam** [comment]
Oh since I implement incorrecly Equaltable protocol. Thank you very much. At the moment, it was fixed
