### ISSUE TITLE
Middleware code 

### ISSUE THREAD

**Issue by mengxiangyue** [ReSwift/ReSwift#288]
I have limited ability to read the middleware code，I wrote the following code, do not know is the same function?
```swift 
public struct Action {}
public struct State {}


typealias Middleware = (Action, State) -> (Action, State)
var loggerMiddleware: Middleware = { action, state in
    print("loggerMiddleware")
    return (action, state)
}

var loggerMiddleware1: Middleware = { action, state in
    print("loggerMiddleware1")
    return (action, state)
}


var customAction = Action()
var customState = State()
let middlewares = [loggerMiddleware, loggerMiddleware1]
for item in middlewares {
    let (action, state) = item(customAction, customState)
    customAction = action
    customState = state
}

/*
print:
loggerMiddleware
loggerMiddleware1
*/
```

**Comment by DivineDominion** [comment]
Do you want to propose a change to `Middleware` to `(Action, State) -> (Action, State)` instead of returning closures?

**Comment by mengxiangyue** [comment]
I just wondered that does i wrote the code has  the same function?

**Comment by DivineDominion** [comment]
Well, for what your example can _do_, maybe. But real `Middleware` allows you to call `dispatch` and thus fire new actions before and/or after the currently processed action is passed on to the reducers. Your example cannot do that.

**Comment by mengxiangyue** [comment]
OK，understand，thank you！

**Comment by DivineDominion** [comment]
You're welcome!
