### ISSUE TITLE
Support subscribing with keypaths in Swift 4

### ISSUE THREAD

**Issue by kdawgwilk** [ReSwift/ReSwift#289]
It would be nice to be able to subscribe to more specific items in the state using keypaths added in Swift 4.  Example of how they were adopted in The SDKs here: https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/AdoptingCocoaDesignPatterns.html#//apple_ref/doc/uid/TP40014216-CH7-ID12

**Comment by danielmartinprieto** [comment]
Hi, @kdawgwilk. Could you explain a little more how the use of keypaths would improve the library? Thanks!

**Comment by kdawgwilk** [comment]
Yeah so here is a brief example:

## Goal

Be able to subscribe with finer grain using KeyPaths like this:
```swift
store.subscribe(self, to: \AppState.someSubState.property)
```

## Implementation Example

Added `Store.swift` method:
```swift
open func subscribe<V, S: StoreSubscriber>(
    _ subscriber: S, to keyPath: KeyPath<State, V>
) where S.StoreSubscriberStateType == V {
    // If the same subscriber is already registered with the store, replace the existing
    // subscription with the new one.
    if let index = subscriptions.index(where: { $0.subscriber === subscriber }) {
        subscriptions.remove(at: index)
    }

    let value = state[keyPath: keyPath]
    print("Value being observed: \(value)")

    // Details left out
}
```

**Comment by kdawgwilk** [comment]
The complete implementation might look like this?
``swift
open func subscribe<V: StateType, S: StoreSubscriber>(
_ subscriber: S, to keyPath: KeyPath<State, V>
) where S.StoreSubscriberStateType == V {
    // If the same subscriber is already registered with the store, replace the existing
    // subscription with the new one.
    if let index = subscriptions.index(where: { $0.subscriber === subscriber }) {
        subscriptions.remove(at: index)
    }

    // Create a subscription for the new subscriber.
    let originalSubscription = Subscription<State>()
    let transformedSubscription = Subscription<V>()

    let subscriptionBox = SubscriptionBox(
        originalSubscription: originalSubscription,
        transformedSubscription: transformedSubscription,
        subscriber: subscriber
    )

    subscriptions.append(subscriptionBox)

    if let state = self.state {
        originalSubscription.newValues(oldState: nil, newState: state)
    }
}
```

**Comment by svdo** [comment]
FYI: I also support this in my library https://github.com/svdo/ReRxSwift.

**Comment by danielmartinprieto** [comment]
@kdawgwilk thanks! Yeah, I think `store.subscribe(self, to: \AppState.someSubState.property)` would be a small but nice syntax improvement to the current way of subscribing using the closure.

**Comment by mjarvis** [comment]
Is this being proposed to be alongside the existing selection method, or instead of? The one thing this lacks is selection of multiple portions of state at once. Otherwise it looks good. If the proposal is in addition to the existing selection methods then I would recommend moving this to a PR, and using `#if swift(>=4.0)` to ensure we don't break 3.2 compatibility.

**Comment by danielmartinprieto** [comment]
Uh, that's true. I wouldn't use it unless it would replace the current implementation, improving it somehow. If that's not the case I'd rather keep a minimal API surface.

**Comment by kdawgwilk** [comment]
This addition would not support multiple selections and if that was needed it would be best to just subscribe to a substate that contains everything you need.  I am not sure if there would be a way to receive changes to more than a single subscription endpoint.  Since the item you subscribe to is passed as a single method parameter.  It would interesting to see if you could subscribe twice and implement two different methods that would get called for each specific item that was subscribed.  Does the current implementation support subscribing to more than one substate?

**Comment by candostdagdeviren** [comment]
AFAIK, I think current implementation doesn't support subscribing to more than one substate. I also prefer not to keep both implementation at the same time. Maybe this proposal good for v5.0 (don't know is there a plan for that) as breaking change.

**Comment by danielmartinprieto** [comment]
Right now you can return whatever you want from the select function when you create a subscription. There, you have access to your whole state, and you can map it to an object including only the substates you care about for that subscription. Note that this doesn't mean you subscribe more than once.

**Comment by kdawgwilk** [comment]
Ah that makes sense, I am not sure how a similar concept would be possible using keypaths

**Comment by DivineDominion** [comment]
Since there was no progress on this for a year, I'll close the issue for now.
