### ISSUE TITLE
Swift 3.2 support

### ISSUE THREAD

**Issue by barteljan** [ReSwift/ReSwift#290]
ReSwift supports Swift 3.2 but README.MD says only Swift 3.0.1

**Comment by DivineDominion** [comment]
Good catch! Want to create a PR with the changes? (Maybe you can spot the same outdated info somewhere else in the help.)

**Comment by candostdagdeviren** [comment]
I opened a PR for this small fix

**Comment by candostdagdeviren** [comment]
#291 fixes this. Closing.
