### ISSUE TITLE
Facing EXC_BAD_ACCESS when projects and states become large and nested

### ISSUE THREAD

**Issue by fans3210** [ReSwift/ReSwift#293]
Hi,
Thanks for the amazing framework. Currently our project are using it heavily. But as the project grows, we are facing problems. The most common one is the 'EXC_BAD_ACCESS' issue.

<img width="1268" alt="00" src="https://user-images.githubusercontent.com/6023208/30856001-8bafa900-a2e9-11e7-81a1-a2969276e942.png">
<img width="1249" alt="11" src="https://user-images.githubusercontent.com/6023208/30856006-8f6d3e68-a2e9-11e7-90c9-3bd4c94ddade.png">
<img width="907" alt="22" src="https://user-images.githubusercontent.com/6023208/30856013-9349f6f2-a2e9-11e7-86d0-1fe072505db8.png">
<img width="907" alt="33" src="https://user-images.githubusercontent.com/6023208/30856016-953c2340-a2e9-11e7-8b97-c17931e52ecd.png">

This happens when I started to add a new state. The app will crash if the state contains one or more enum properties with associated value. If I simply changed the state to a simpler struct, the app won't crash most of the times. Sometimes, crash also happened when I tried to add a substate inside another substate(Eg: add a state in EntitiesState.  I have to move that substate out of the EntitiesState to avoid the crash).

This only happens when we have about hundreds of different states and substates.

I would be very appreciated if you could give me some help. Thanks a lot!

**Comment by DivineDominion** [comment]
My states are far more deeply nested without problems. Are you 100% certain there are no reference types involved?

**Comment by amreshkumar** [comment]
@fans3210 You could try putting logs in init and deinit of EntitiesState – that may help unveil actual issue. As @DivineDominion said – with value types you are very unlikely to get an EXC_BAD_ACCESS unless there is a reference type involved.

**Comment by fans3210** [comment]
Hi @DivineDominion and @amreshkumar . Thanks for the quick reply. I've gone through all our states and confirmed all of them are value types, with their properties too. And the EXC_BAD_ACCESS issue might not only happen in EntitiesState, but also could happen in the main AppState. 
The only condition that some states might interact with reference types are in their extensions. Eg: we used ObjectMapper frameworks for json parsing for some properties of a state and 'map' is a reference type.

extension AppState: Mappable {
    public init?(map: Map) {
    }
    
    public mutating func mapping(map: Map) {
        userAuthState <- map["userAuthState"]
        chatState <- map["chatState"]
    }
}

Another example is the conversion between our value type models and NSManagedObjects. But all these are handled by extensions and shouldn't have any issue with the EXC_BAD_ACCESS

**Comment by fans3210** [comment]
@amreshkumar . The crash always happen in this line:

```
public func appReducer(action: Action, state: AppState?) -> AppState {
    var state = state ?? AppState() //this is where the crash happens, the AppState init is not even called since the crash happens before the checking of the optional state value
```

**Comment by DivineDominion** [comment]
I vaguely recall I had a mind-boggling issue like this a few months ago, too. Not related to ReSwift, but to reading a perfectly fine optional value type instance. In my case it turned out something completely different did mess with the memory; it was something like a weak NSTextView reference (unbeknownst to me, weak references were not supported until 10.12!) -- anyway, it didn't have anything to do with the reported line at all.

Could be totally off-track with this wild-ass guess :) If you want to check this out, I suggest you remove a huge part of the app code _except ReSwift_ and then see if the error goes away at all, i.e. if it is an issue like I had.

**Comment by buscarini** [comment]
Are you using Xcode 8 and running in the Device in debug mode? There was a swift compiler bug in Xcode 8. If this is the case you can try upgrading to Xcode 9 or enabling optimizations. There is a workaround but I think it didn't work for us.

**Comment by fans3210** [comment]
Thanks @DivineDominion for your suggestions.
@buscarini . Yes I was using xcode 8 before but I have already upgraded to xcode 9 with swift 3.2. Unfortunately I still faced such issue sometimes.

**Comment by amreshkumar** [comment]
@fans3210 I'm able to see similar behavior in my project. But instead of crashing it is a memory leak and it seems to be harmless for now. Can anyone else try to instrument with Leaks? I'm using Xcode 9/Swift 3.2

**Comment by mjarvis** [comment]
@amreshkumar Perhaps the memory leak you're seeing is https://github.com/ReSwift/ReSwift/pull/278 ? Does it go away if you use latest master instead of `4.0.0`? We should probably think about making a 4.1 release with the latest changes.

**Comment by DivineDominion** [comment]
@fans3210 any progress on this?

**Comment by fans3210** [comment]
@DivineDominion . No update for now since we didn't face such problems recently. I will report again if there is further issue. Thanks a lot

**Comment by fans3210** [comment]
@DivineDominion @amreshkumar . The issue comes again after I merged my teammates' work which introduced a large number of new states

**Comment by fans3210** [comment]
Currently 3 developers of our project are having the same issue. 
The crash only happened on devices, not simulator

**Comment by amreshkumar** [comment]
@fans3210 can you try debugging with zombies enabled. It will help in understanding the problem better.

**Comment by Dimillian** [comment]
maybe link to mine #301 ? Is code optimisation turned off or on?

**Comment by fans3210** [comment]
@Dimillian , yes it's on. But my crash has nothing to do with the optimisation

**Comment by Dimillian** [comment]
@fans3210 Too bad. I'm worked with a quite complexe store, with a lot of structure. Got no crash in debug. What properties and complexity did you remove for example?

**Comment by DivineDominion** [comment]
This is weird. I'd love to have a private look at your code commits before and after, maybe some day in December via Skype, so someone on the ReSwift team here has seen firsthand what causes crashes -- and how you fixed them. Email me if your team is interested.

**Comment by fans3210** [comment]
@DivineDominion . Sure, I will let my team leader know
