### ISSUE TITLE
update Reducer documentation for ReSwift 4

### ISSUE THREAD

**Issue by DivineDominion** [ReSwift/ReSwift#294]
As per https://gitter.im/ReSwift/public?at=59c97bf7bc46472974754f70 it seems the docs are outdated

**Comment by mjarvis** [comment]
I'm unable to find any outdated documentation. Searching `reducer` https://github.com/ReSwift/ReSwift/search?p=1&q=reducer in the project shows no more references to `AnyReducer`. The getting started guide & other docs seem to correctly reference `Reducer<ReducerStateType>`

**Comment by DivineDominion** [comment]
I now checked at home and, yeah, false alarm. Sorry!
