### ISSUE TITLE
Default skipRepeates when State conforms equatable only works for top level subscribers

### ISSUE THREAD

**Issue by danielmartinprieto** [ReSwift/ReSwift#298]
Hi!

I've recently seen something in my app that I find weird, and I think it's because I'm not understanding how the default behaviour for subscriptions works when the state conforms equatable.

All my state is equatable, so when I create a subscription using `select { ... }`, I expect the subscriber to be notified only when the substate of the subscription has changed, but this seems not to be the case. If I add `skipRepeats()` after the select, then it works, but per the [documentation](https://github.com/ReSwift/ReSwift/blob/master/Docs/Getting%20Started%20Guide.md), concretely 

> For example, one requirement may be to notify subscribers only when the state they are interested in has changed. This is the default Store setting. 

I wasn't expecting that I should add `skipRepeats()` every time I use `select { ... }`.

I checked the [code](https://github.com/ReSwift/ReSwift/blob/master/ReSwift/CoreTypes/Store.swift#L198) and it seems that indeed it would work only if I subscribe to the top level (the whole state). See `open func subscribe<S: StoreSubscriber>(_ subscriber: S) where S.StoreSubscriberStateType == State`.

So I don't know if I don't understand the docs properly, or the code, or there is something else that I'm missing. Ideally, by default I should be able to subscribe to a substate automatically skipping repeats if my whole state conforms Equatable, right? And, actually, I would say this was like this before and it changed at some point.

Thanks!

**Comment by danielmartinprieto** [comment]
@DivineDominion hey, do you know something about this?

**Comment by DivineDominion** [comment]
Ok, so even though `state.subscriptionsAutomaticallySkipRepeats` is `true`, after you `select` a substate, you get identical results? That sounds not like what I'd expect, too. 

Of course I don't have all the code memorized :) Looking at [how the auto-skipping works](https://github.com/ReSwift/ReSwift/blob/master/ReSwift/CoreTypes/Store.swift#L198), `skipRepeats` seems to be called on the initial super-state, not the substate, which is kind of wasteful, too.

I'm on a very tight schedule right now and cannot spend as much time to work on this. If you could add some failing unit tests in a PR, we could move this issue forward together towards a solution.

**Comment by danielmartinprieto** [comment]
Cool! I will put something together soon.

**Comment by danielmartinprieto** [comment]
Done! https://github.com/ReSwift/ReSwift/pull/299

**Comment by JoeCherry** [comment]
#300 Has a potential fix
