### ISSUE TITLE
Memory Leaks reported

### ISSUE THREAD

**Issue by Sethuraman** [ReSwift/ReSwift#302]
While we were profiling our app we noticed there were a few memory leaks reported. We looked up the object graph and found the below reference cycle around the subscriptions in ReSwift.

Could someone take a look and let me know if this a problem in the way we are subscribing?

`store.subscribe(self) { $0.select {$0.someSubState}.skipRepeats {$0 == $1 }}`

![leak_cycles__subscription_myheuristicsscreenstate___-_0x1c0236ec0](https://user-images.githubusercontent.com/1607090/32640032-a4cd083a-c5ec-11e7-9752-e2e85cc6f077.png)

**Comment by Ben-G** [comment]
@Sethuraman thanks for reporting! Are you using the 4.0.0 release or the `master` branch? https://github.com/ReSwift/ReSwift/pull/278 might have fixed this issue?

**Comment by Sethuraman** [comment]
I am using the 4.0.0 release. I will check the master branch and get back

**Comment by Sethuraman** [comment]
@Ben-G - I can confirm that the master branch fix works. Would you know when is the next likely release for ReSwift?

**Comment by amreshkumar** [comment]
@Sethuraman Glad you asked :) @Ben-G (referring to this - https://twitter.com/benjaminencz/status/928904354417045506) can we modify this ticket to track a patch release?

**Comment by DivineDominion** [comment]
I'll take care of that in a second in a separate issue!
