### ISSUE TITLE
Enable - Allow app extension API only

### ISSUE THREAD

**Issue by amreshkumar** [ReSwift/ReSwift#304]
ReSwift should be usable across widgets and iMessage targets. To be able to do that "Allow app extension API only" should be enabled.

**Comment by amreshkumar** [comment]
When used with cocoapod this setting can be set in Pods project. But is there a way to resolve this while using carthage?

**Comment by DivineDominion** [comment]
I recently discovered this when checking the library target's build settings for RxSwift. I have 0 experience with app extensions; can you try flicking the build setting and see what happens? This should directly affect Carthage (while CocoaPods basically provides a build settings override which can become redundant this way, too).
