### ISSUE TITLE
Cocoapod update

### ISSUE THREAD

**Issue by aler** [ReSwift/ReSwift#311]
Could you please update cocoapod spec version to include all fixes have been made since version 4.0?

**Comment by mjarvis** [comment]
Hi @aler, We're currently waiting on @Ben-G or @agentk to publish [4.0.1](https://github.com/ReSwift/ReSwift/releases/tag/untagged-f47ec39b635d493d988a) and update the CocoaPods entry. They are currently the only ones with access to the Cocoapods trunk registration for ReSwift.

**Comment by Ben-G** [comment]
Sorry for the delay. Have been traveling with spotty internet. I forgot about CocoaPods permissions - that needs to be fixed. 

Will take care of that!

**Comment by Ben-G** [comment]
@mjarvis @DivineDominion can you give me your email addresses associated with CocoaPods, such that I can add both of you as Pod owners?

**Comment by mjarvis** [comment]
@Ben-G Thanks! I've provided my email address to you on Gitter.

**Comment by mjarvis** [comment]
[4.0.1](https://github.com/ReSwift/ReSwift/releases/tag/4.0.1) has been released 🎉

**Comment by brownsoo** [comment]
👍🏽
