### ISSUE TITLE
Good Practices for a navigation with "endless" screens

### ISSUE THREAD

**Issue by Uzaak** [ReSwift/ReSwift#320]
I have a shopping app and have been struggling to use ReSwift in it.

If I had a simple straightforward navigation, where users would Search, then see a list of results, and check the details of a specific Product, the use seems quite simple. I take it all I'd need is one SearchState with keyword, resultList and product (for the details screen)... like this:

```Swift
struct SearchState: StateType {
    var keyword: String?
    var resultList: [Products]?
    var product: Product?
}
```

However, users like to see similar products, and the conversion is much higher if I let users navigate however they like. For example, an user might search for Android, find a phone, see an iPhone as a related product, navigate to it, and keep going as far as he or she wants. While this makes for a higher conversion and happier users, I can't seem to find an adequate model to use ReSwift once the user can find himself in a stack composed of any number of "ResultListViewControllers" and any number of "ProductViewControllers" arranged in any order. They can then go back, through the NavigationController, to whichever screen they like all the way to the very beginning.

Is there any way to model such thing in a State?

**Comment by DivineDominion** [comment]
Sure there is, but it depends on you and your app what makes sense, in the end!

Here's one untested idea I have in mind but never found a chance to test:

- make sure result listings and product details are their own self-contained objects that are ready for display on their own (i.e. no dependency on other substates through uncohesive and tight coupling) 
- put both of these data in a dictionary with a UUID as the key (you can think of this as a state cache)
- maintain the ordered stack as a list of UUIDs
- add "push" and "pop" actions to navigate in the stack of views

This will not scale forever: at some point, the cache dictionary might grow too large when you keep downloaded images etc. in it, which I recommend to do at first for a naive attempt. You're gonna need to create abstractions, then, like FullyDownloadedProductDetails vs OnlyTheRemoteServerRequestIsStoredButAllDataIsRemovedFromMemoryProductDetails.

**Comment by Uzaak** [comment]
@DivineDominion I've gone that far already (minus the UUID idea, but plus some shenanigans involving the Navigation stack itself), but stopped due to the high possibility of a programmer mistake of adding or removing a controller without touching the State stack. Re-thinking of it after reading your suggestion gave me two maybe obvious but still new ideas:
1) The addition or removal from the State stack itself can trigger the push or pop;
2) Maybe working with a simple, unordered dictionary since mistakingly leaving stuff there wouldn't harm the app (and it would be cleaned everytime the flow starts over from the beginning).

I'll have to dig further into these two solutions. Some useful information:
- No need to worry about memory, my objects are small enough that an array of 1 million products can still be managed (not that it should, but I've tested it that far using an iPhone 5s, out of curiosity, so...)
- Some data does come from the internet, but it is ok to think of the objects as self-contained and ready to display

**Comment by DivineDominion** [comment]
Oh yes, I got the push/pop stuff wrong: you need actions to call push/pop for the stack of identifiers, and then have a service object figure out what to do with the navigation controller, which I forgot is also called pushing to/popping from the navigation stack. Otherwise I think that should just work.

**Comment by juniorgarcia** [comment]
If I may tell you something, I have a concern about the use of ReSwift.

Let's imagine that a user is on that infinite auto-loading scrolls, like Facebook or Instagram. Using ReSwift can be a problem as the object grows and grows? This might be hard to tell, I know.

Is there a diff algorithm that enhances the generation of a new state, since it's never modified, but "duplicated".

Maybe this is just misconception or fear, but I become worried when it comes to a huge state on the application that can fill too much memory.
