### ISSUE TITLE
Multiple Stores?

### ISSUE THREAD

**Issue by RabbitMC** [ReSwift/ReSwift#322]
Hi,

is it allowed to have more than one store? 

Thanks :)

**Comment by DivineDominion** [comment]
Yes, each store instance is independent. It's similar to creating various `NSNotificationCenter` instances.

I have used this with great success in a macOS app with `NSDocument`, where each document had its own store.

**Comment by RabbitMC** [comment]
Hey @DivineDominion,
thanks for clarification.
