### ISSUE TITLE
Trying to override subscribe method -> cannot override more than one superclass declaration

### ISSUE THREAD

**Issue by stevenb9** [ReSwift/ReSwift#323]
I'm trying to create a mock class for the Store, i've got following code which throws an error when overriding subscribe:

```
import Foundation
import Quick
import Nimble
import RxSwift
@testable import MainProject
@testable import ReSwift

    class MockReSwiftStore: ReSwift.Store<MainState> {
    var dispatchDidRun: Bool = false
    var subscribeWasTriggered: Bool = false

    init() {
        let reducer: Reducer<MainState> = {_, _  in MainState() }
        super.init(reducer: reducer, state: nil)
    }

    required init(
        reducer: @escaping (Action, State?) -> State,
        state: State?,
        middleware: [(@escaping DispatchFunction, @escaping () -> State?) -> (@escaping DispatchFunction) -> DispatchFunction]) {
        super.init(reducer: reducer, state: state, middleware: middleware)
    }

    override func subscribe<SelectedState, S>(
        _ subscriber: S,
        transform: ((Subscription<MainState>) -> Subscription<SelectedState>)?)
        where S: StoreSubscriber,

        S.StoreSubscriberStateType == SelectedState {
            subscribeWasTriggered = true
        }
    }
}
```

But when compiling I get : "Declaration 'subscribe' cannot override more than one superclass declaration"
<img width="411" alt="screen shot 2018-01-25 at 12 25 32" src="https://user-images.githubusercontent.com/24360476/35386580-d3a7b62a-01cc-11e8-8511-b5a4ba8744f7.png">

Then when using Xcode's autofill It does also see two functions
<img width="1166" alt="screen shot 2018-01-25 at 12 21 11" src="https://user-images.githubusercontent.com/24360476/35386579-d38a9dc4-01cc-11e8-92fb-8425bed533b5.png">

This is the compiler error
<img width="1044" alt="screen shot 2018-01-25 at 12 31 45" src="https://user-images.githubusercontent.com/24360476/35386581-d3d13fd6-01cc-11e8-8918-21e2c290c467.png">

This error appeared after updating from reSwift 3.x -> 4.0.1
also: https://stackoverflow.com/questions/48441920/declaration-subscribe-cannot-override-more-than-one-superclass-declaration-re

**Comment by DivineDominion** [comment]
I'll ignore the regression from v3 to v4 for now :)

My thin layer of glue code that performs the subscription for all subscribable service objects is exercised indirectly through state updates. It's how ReSwift's own tests work, too:

```swift
class MainWireframeTests: XCTestCase {
    func testActivate_SubscribesStoreNoteDraft() {

        let storeNoteDraftDouble = StoreNoteDraftDouble()
        service.activate(configuration: createMainRoute(draftNote: storeNoteDraftDouble))
        storeNoteDraftDouble.reset() // Subscribing itself passes current state already; reset for the test

        storeDouble.dispatch(IrrelevantTracerAction())

        XCTAssertTrue(storeNoteDraftDouble.didReceiveState)
    }
    class StoreNoteDraftDouble: NullStoreNoteDraft {

        var didReceiveState = false
        override func newState(state: DraftState) {
            didReceiveState = true
        }

        func reset() {
            didReceiveState = false
        }
    }
}

struct IrrelevantTracerAction: ReSwift.Action {}
```

I see why you'd want to assert the fact of an object being subscribed itself. I have no conclusive answer as to why you should drop this line of thinking, of if you should at all. The principle "Only mock objects you own" states this in a positive way, but its reasons are not technical -- as opposed to your quarrel with Swift. For conceptual purity, you'd need to wrap the subscription process in your own object and mock _that_. Though that might not really be useful.

Although mostly unrelated, I use something like this to test action dispatching (without actually affecting reducers or middleware).

```swift
//  Copyright © 2017 Christian Tietze. All rights reserved. Distributed under the MIT License.

@testable import TheArchive
import ReSwift
import State

class DefaultStoreRecording {

    init() {
        self.store = nullDefaultStore()
        self.store.dispatchFunction = { action in
            self.actions.append(action)
            return ()
        }
    }

    let store: DefaultStore
    var actions = [Action]()
    var firstAction: Action? { return actions.first }
    var didRecordAction: Bool { return actions.isNotEmpty }

    func reset() {
        actions = []
    }
}

```
