### ISSUE TITLE
<< error type >> inside $0.select closures

### ISSUE THREAD

**Issue by AlexanderBollbach** [ReSwift/ReSwift#326]
I'm been noticing autocompletion bugginess while inside of my store sub-selection closures.

e.g. in,
```
store.subscribe(self) {
    $0.select {
        guard let foo = $0.foo else { return nil }
        foo. // foo will not suggest anything and read as << error type >> in the autocomplete pop up.
    }
}
```

note sure if this is particular to a bad xcode i'm running.  Or the current sourceKit stuff is just not working properly inside doubly nested closures using unnamed arguments?

**Comment by AlexanderBollbach** [comment]
ah just rubber duck debugged myself and tried using `appState -> ReturnType in` instead of `$0` and autocompletion works.  i suppose i can close this?  SourceKit/Swift/Xcode bug though?

**Comment by mjarvis** [comment]
I've encountered this before as well. We're not doing anything funky, it must be a SourceKit bug.
