### ISSUE TITLE
Ambiguous reference to member 'subscribe'

### ISSUE THREAD

**Issue by NickJorgensen** [ReSwift/ReSwift#329]
Hello 

I am using ReSwift in a Watchkit Extension and whenever I try to subscribe to mainStore I get the following error

"Ambiguous reference to member 'subscribe'"

my subscription code looks like
`mainStore.subscribe(self)`

I have created the mainStore the same way as recommended in the docs

`let mainStore = Store<ReAppState>(
    reducer: WatchReducer,
    state: nil
) as Store`

Except because this is a Watchkit App it is created in ExtensionDelegate.swift

Its strange because I have another watch app that is using ReSwift just fine and have been attempting to compare the two but don't see anything different so i think I might be missing something obvious.

**Comment by NickJorgensen** [comment]
Solved the problem.

This is not an issue with ReSwift.  

I previously created an object in my source code that I named AppState and i had earlier renamed ReSwifts AppState to ReAppState.

**Comment by mjarvis** [comment]
Thanks for the update, @NickJorgensen, I'm glad you were able to solve the problem :)
