### ISSUE TITLE
Do reswift support sub stores?

### ISSUE THREAD

**Issue by gkmrakesh** [ReSwift/ReSwift#331]
We are building a product consist of

1. multiple modules
2. REDUX

Note: The whole project going to be the combination of these modules!

We are planning for independent modules which have its own sub stores and the ability to talk between modules?

Please let me know, Any solution possible with ReSwift?

**Comment by DivineDominion** [comment]
You can create as many Stores as you like, in as many modules as you want. Syncing changes becomes harder, and ReSwift is designed to have 1 store for the while app state. You'll be better off creating ModuleState1, ModuleState2, ModuleState3, ... and combine them in a single AppState. Then one store will do the trick. See https://github.com/ReSwift/ReSwift/issues/377 for a discussionon that.

If you find you need to have multiple stores, maybe ReSwift isn't a good fit, though, and a more general-purpose reactive library like RxSwift with some local state can help.
