### ISSUE TITLE
Ambiguous reference to member 'subscribe(_:transform:)'

### ISSUE THREAD

**Issue by krema** [ReSwift/ReSwift#332]
I cannot explain why the compiler can't compile this minimal example. 
For the line store.subscribe(self) I always get Ambiguous reference to member 'subscribe(_:transform:)
Did I miss something or is that a bug? 

Version: 4.0.1
Swift: 4.0

I would appreciate any help. Thanks

    struct AppState: StateType {
        var studentState: StudentState
    }
    struct StudentState: StateType {
        var students: [String: [Student]] = [:]
    }

    let store = Store<AppState>(
         reducer: appReducer,
         state: AppState(studentState: StudentState())
    )

    class StudentVC: UIViewController, StoreSubscriber {
        override func viewWillAppear(_ animated: Bool) {
            store.subscribe(self) { <--------- Ambiguous reference to member 'subscribe(_:transform:)
                $0.select {
                    $0.studentState
                }
            }
        }

        func newState(state: StudentState) {
        }
    }

**Comment by mjarvis** [comment]
@krema The error is occuring because you're returning `($0.studentState.students)` which is of type `(StudentState)` (note the `()` making it a tuple), but then you're referencing `state: StudentState` below.
You can resolve this by removing the parenthesis from the `select` return value.

**Comment by amreshkumar** [comment]
I think the issue is that you can only subscribe to sub-states defined in AppState. Which in this case should be **$0.studentState** and not **$0.studentState.students**

**Comment by mjarvis** [comment]
Ah, yes, thats also causing an issue, since `$0.studentState.students` is `[String: [Student]]`
You could select that, but then you'd need `func newState(state: [String: [Student]])` instead of `state: StudentState`

**Comment by krema** [comment]
@mjarvis & @amreshkumar 
Thanks for the quick response. I updated the code above with your suggestions 

- Removing the parenthesis 
- $0.studentState instead of $0.studentState.students

but still get the same problem.

**Comment by mjarvis** [comment]
Perhaps clean & build, or restart xcode/your computer? I just tested the following:

```swift
import ReSwift

struct Student {}

struct AppState: StateType {
    var studentState: StudentState
}
struct StudentState: StateType {
    var students: [String: [Student]] = [:]
}
func appReducer(_ action: Action, state: AppState?) -> AppState {
    return state ?? AppState(studentState: StudentState())
}

let store = Store<AppState>(
    reducer: appReducer,
    state: AppState(studentState: StudentState())
)

class StudentVC: NSObject, StoreSubscriber {
    func start() {
        store.subscribe(self) {
            $0.select {
                $0.studentState
            }
        }
    }

    func newState(state: StudentState) {
    }
}
```
And it compiles successfully.

**Comment by krema** [comment]
Thank you for your help. I found the problem.  :sweat_smile:

This line caused the issue:

    typealias StoreSubscriberStateType = AppState

Wow 😄
