### ISSUE TITLE
Question about skipRepeats behavior with Equatable

### ISSUE THREAD

**Issue by dastan28** [ReSwift/ReSwift#337]
I wonder if my understating about **skipRepeats** behavior is correct.
Let's say I have AppState 
```
struct AppState: StateType {
   var equatableObject: EquatableObject
   var nonEquatableObject: NonEquatableObject
}
```
I subscribe to only equatableObject variable changes like `subscribe(self) {$0.select {$0. equatableObject}}`. Then I've noticed that my StoreSubscriber function `func newState(state: EquatableObject)` is also called when changes on nonEquatableObject happens. Is It normal behavior or I miss something in my architecture? I've also noticed that if I use manual .skipRepeats checking then it doesn't happen.
Thanks forward.

**Comment by DivineDominion** [comment]
@dastan28 Sorry for overlooking this issue _for a year!_ When you change any inner state, the root `AppState` will be mutated as well, and from there `newState` callbacks will be invoked for every subscriber. `skipRepeats` makes sure you only get notified of changes to the part your subscriber is interested in.
