### ISSUE TITLE
Setup a peril instance for the ReSwift organization

### ISSUE THREAD

**Issue by SD10** [ReSwift/ReSwift#339]
Hello ReSwift team members,

I noticed that @Ben-G invites new contributors to ReSwift after their first merged PR. At [Moya](https://github.com/Moya), we do the same thing and have gone so far as to [automate the process](https://github.com/Moya/Moya/pull/1640#issuecomment-381720452).

We use [peril](https://github.com/danger/peril) (which is similar to Danger, but listens to any GitHub event hook and not just PRs) to listen for merged PR's and then automatically invite users to the org using a [script](https://github.com/Moya/moya-peril/blob/master/org/aeryn.ts).

If one of the owners of the organization is willing to [setup the initial peril server](https://github.com/danger/peril/blob/master/docs/setup_for_org.md), I could help you automate this as well as potentially other things around the ReSwift organization.

**Comment by Ben-G** [comment]
Ah, thanks a lot for this suggestion. This is something I meant to do for a long time, but haven't gotten to any significant open source work in 2018. If I were to make you an organizer, would you be willing to configure the peril server as well?

**Comment by SD10** [comment]
@Ben-G Only owners of the organization can setup peril because it requires creating a new GitHub application. I'm not sure how you feel about making a stranger an owner of your org. However, if you feel comfortable you could temporarily upgrade my permissions and I would be willing to help you out. I can acknowledge that setting this up is a bit tedious 😕

**Comment by mjarvis** [comment]
I might have time to do this in a week or two if @Ben-G is uncomfortable upgrading your permissions.

**Comment by Ben-G** [comment]
To me @SD10 has sufficient public credentials! Gave you owner permissions for now.

**Comment by SD10** [comment]
@Ben-G Received. Thanks for the vote of confidence! 😊 
I'm stoked to get peril running on another organization in production 💯

**Comment by mjarvis** [comment]
@SD10 Hi Steven, Just checking up on the status of this, I've noticed we're getting comments in PRs saying that peril/danger failed to run. An example can be found in https://github.com/ReSwift/ReSwift/pull/365
If this has been put on hold, would it be possible to disable the comments for the time being?

**Comment by SD10** [comment]
@mjarvis Thanks for reporting this to me. I'll fix it (or disable it if it can't be fixed 🤔) tonight

**Comment by SD10** [comment]
@mjarvis Quick feedback loop 😆 I've fixed it. Peril just didn't have the proper permissions to invite a user to the ReSwift organization. If you see that this issue persists don't hesitate to give me a holler. Sorry for the inconvenience
