### ISSUE TITLE
Is there any way to implement skip repeat with out state being equitable 

### ISSUE THREAD

**Issue by coderMemberam** [ReSwift/ReSwift#345]
Hello,

is it mandatory to implement equitable for skip repeat?

it is hard to implement equitable for all states, is there any workaround?

Example:
I want to avoid making all my states manually Equatable(like below) yet work with skip repeat.

```
struct Counter: Equatable {
    var data:Int=0
    
    public static func ==(lhs: Counter, rhs: Counter) -> Bool {
        return lhs.data == rhs.data
    }
}

```
Thanks in advance

**Comment by DivineDominion** [comment]
When your state isn't `Equatable`, you can pass a block to `skipRepeats` and do whatever you want inside. See: https://github.com/ReSwift/ReSwift/blob/master/ReSwift/CoreTypes/Subscription.swift#L98

**Comment by coderMemberam** [comment]
is there any way to make all my states equatable by default so that when I subscribe to multiple states, I can listen to only changed states.

**Comment by DivineDominion** [comment]
You have to conform to `Equatable` on your own, I'm afraid. And if you want to subscribe to a selection of substates, you have to provide the `skipRepeats` implementation of the combined selection tuple, too :)

**Comment by DivineDominion** [comment]
You can, if you make it `class Counter` :)

**Comment by coderMemberam** [comment]
Can you please share how to do that?

I have tried a couple of ways and failed!!

**Comment by DivineDominion** [comment]
I don't think your reasons to look for reference type semantics are good (i.e. "Equatable conformance gets on my nerves"), but if you have problems with `class` states, please share details in #346

**Comment by mjarvis** [comment]
@coderMemberam Swift auto-generates `Equatable` conformance for structs. Theres no need to manually implement `func ==` if all sub-types are Equatable. The following compiles & works as appropriate:

```swift
struct Foo: Equatable {
    var a: Int
    var b: Int
}

Foo(a: 1, b: 2) == Foo(a: 1, b: 2) // true
```

**Comment by coderMemberam** [comment]
I am getting below compilation issue!!

<img width="992" alt="screen shot 2018-05-10 at 9 54 37 pm" src="https://user-images.githubusercontent.com/39150656/39880972-f6f84ff4-549c-11e8-90e7-e75023aa5c5e.png">

App State: 
```
import ReSwift

struct AppState: StateType {
    var counter=Counter()
    var counter2=Counter2()
}
struct Counter: Equatable {
    var data:Int=0
    
}

struct Counter2 {
    var data:Int=0
}

```
Reducer: 

```
import ReSwift

// the reducer is responsible for evolving the application state based
// on the actions it receives
func handleAction(action: Action, state: AppState?) -> AppState {
    
    // if no state has been provided, create the default state
    var state = state ?? AppState()
    
    switch action {
    case _ as CounterActionIncrease:
        state.counter.data += 1
    case _ as CounterActionDecrease:
        state.counter.data -= 1
    case _ as CounterActionIncrease2:
        state.counter2.data += 1
    case _ as CounterActionDecrease2:
        state.counter2.data -= 1
    case _ as CounterAction1Static:
        state.counter.data = state.counter.data
    case _ as CounterAction2Static:
        state.counter2.data = state.counter2.data
    default:
        break
    }
    
    return state
}

```

Subscription:

```
override func viewDidLoad() {
        super.viewDidLoad()
        
        mainStore.subscribe(self.state1Subscriber) { state in
            state
                .select { state in state.counter }
                .skipRepeats{ $0 === $1 }
        }
}
```

**Comment by mjarvis** [comment]
@coderMemberam What version of Xcode are you using? That exact code compiles just fine for me.

**Comment by coderMemberam** [comment]
xcode Version 9.2

**Comment by mjarvis** [comment]
You'll need to update to 9.3 to get auto equatable conformance.

**Comment by coderMemberam** [comment]
Does that won't create the problem, because my **iOS APP** support is from iOS 9.0

**Comment by mjarvis** [comment]
No, you can continue to deploy for all the way back to iOS 8.0 with Xcode 9.3.

**Comment by coderMemberam** [comment]
oh, thank you. I have to download latest XCODE. I will try it and post here for any help.
