### ISSUE TITLE
Using class for states and actions instead of struct, what is the difference?

### ISSUE THREAD

**Issue by coderMemberam** [ReSwift/ReSwift#346]

**Comment by DivineDominion** [comment]
You get all the benefits of `class`/reference types, and all the problems. For example, when a subscriber receives a state update and processes it asychronously, there can be race conditions when a new state update is reduced and affects the very same object instance you are still processing on another queue. Value types stay as they are when they are received, which makes things a bit simpler.

**Comment by DivineDominion** [comment]
I'll go ahead and close this one as your other questions tackle this already. Please have a look at our gitter chat for non-issue related questions: https://gitter.im/ReSwift/public
