### ISSUE TITLE
State should be immutable?

### ISSUE THREAD

**Issue by nyeu** [ReSwift/ReSwift#351]
Hi! I have a question related to the State and the Reducers.

In your documentation it says that 
> Reducers provide pure functions, that based on the current action and the current app state, create a new app state

But what you actually do in all your code samples is basically _modifying_ the state, rather than returning a new one. 
I thought that one of the points of Redux was to have an immutable state, so the reducers take an state and action and construct and return a new state.

To me, what it would make sense is that every variable in the state should be a constant. This would force you to create a new state in the reducer. 
I would love to know your thoughts about this and what is the best practice.

Thank you for ReSwift, is amazing :)

**Comment by DivineDominion** [comment]
When you use a `mutating` function or change the value of a `var` property in Swift structs, you bypass having to call the initializer with `1` change and `N-1` unchanged parameters (where N is the number of properties in your type).

Imagine a type with 30 properties -- that would be very noisy in the reducers!

So the modification is creating a mutated copy, which is about the same as creating a new instance from scratch.
