### ISSUE TITLE
Initial state and @connect?

### ISSUE THREAD

**Issue by Dimillian** [ReSwift/ReSwift#355]
Let's say we decide to put the state property of the store to private. 
How would you set the initial state of your UI components ? 

With React/Redux the connect is called at the first render pass, you don't need any state modification for it to be called the first time. 
With ReSwift (and ReKotlin), the newState is not called after the subscribe. So if you don't have access to your store.state anymore, you can't set the initial state of your components anymore. 

Do we have any solution for that? Because in fact I would love to stop accessing my states outside of newState, but for now it's not really possible with the current implementation.

**Comment by mjarvis** [comment]
> With ReSwift (and ReKotlin), the newState is not called after the subscribe

This is not true. ReSwift calls `newState` immediately for new subscribers.

**Comment by Dimillian** [comment]
I was sure it was not, now I'm wrong and I can fix some stuff ;)
