### ISSUE TITLE
Question about MVVM like architecture and states

### ISSUE THREAD

**Issue by ranhsd** [ReSwift/ReSwift#357]
Hi, Lately I had the chance to see some example projects of ReSwift. 
I noticed that part of the projects are implementing the MVVM like approach. Where the view model is a struct which get a state and then calculate some properties like: String, Bool and more which effect the view. I really liked this concept because it decouple the state from the view and view controllers. 

A very good example is this project: https://github.com/cardoso/ReduxMovieDB

There inside the **MovieListViewController.swift** it init the state view model instead of subscribing to the state directly (like in ReSwift docs). The subscribe code looks like the following: 

```
mainStore.subscribe(self, transform: {
            $0.select(MovieListViewState.init)
})
```

The MovieListViewState looks like the following: 

```
struct MovieListViewState {
    let movies: [Movie]
    let searchBarText: String
    let searchBarShowsCancel: Bool
    let searchBarFirstResponder: Bool

    init(_ state: MainState) {
        movies = state.movies

        switch state.search {
        case .canceled:
            searchBarText = ""
            searchBarShowsCancel = false
            searchBarFirstResponder = false
        case .ready:
            searchBarText = ""
            searchBarShowsCancel = true
            searchBarFirstResponder = true
        case .searching(let text):
            searchBarText = text
            searchBarShowsCancel = true
            searchBarFirstResponder = true

        }
    }
}
```

As you can see from the code above. It gets a main state (or sub state) and then calculate and create only the relevant properties for the view. 
Inside the view controller newState delegate the view controller now gets an instance of the **view model** and not instance of the state. 

```
extension MovieListViewController: StoreSubscriber {
    typealias StoreSubscriberStateType = MovieListViewState

    func newState(state: MovieListViewState) {
        movies = state.movies
        moviesTableView.reloadData()

        searchBar.text = state.searchBarText
        searchBar.showsCancelButton = state.searchBarShowsCancel

        switch (searchBar.isFirstResponder, state.searchBarFirstResponder) {
        case (true, false): searchBar.resignFirstResponder()
        case (false, true): searchBar.becomeFirstResponder()
        default: break
        }
    }
}
```

I really love this approach because all the calculation of what need to present/hide or modify moved to the view model responsibility and are not being calculated on the reducer. This keeps the reducer very simple. 

**The issue with this approach**

I tried to run and debug some projects which leverage this nice approach and found that the view model init function are being triggered each time that an action is being dispatched. The problem with it is that in mid-size of big projects a lot of actions are being dispatched for any kind of operations. I tried to use **Skip Repeats** by adding **Equatable** to the state view model but it still calling the init each time an action is being dispatched. 

What I can do is to still subscribe to the state and inside the new state to create the state view model and continue from there, but I think the first option is much nicer and more flexible

So I wanted to know if somebody here face the same situation or maybe somebody have an idea on how to solve it.

Thanks!

**Comment by DivineDominion** [comment]
Now that's a clever and not really intended use of `select`! 

When you tried to skip repeats, how'd you write that? Did you try this?

```swift
mainStore.subscribe(self, transform: {
    $0.skip(when: { _ in true }).select(MovieListViewState.init)
})
```

... to verify that now the initializer is _never_ called and the newState is always skipped?

**Comment by ranhsd** [comment]
Hi @DivineDominion  Will try it and will let you know

**Comment by ranhsd** [comment]
Hi @DivineDominion I am not able to skip. I get a syntax error when I am trying to do it. I tried with SkipRepeats() but it still calling the init method a lot of times

**Comment by DivineDominion** [comment]
Well, we should find out why that doesn't compile, though. Details?

**Comment by ranhsd** [comment]
Hi @DivineDominion it looks like it is related to the StoreSubscriber type 

See attached image:

<img width="810" alt="screen shot 2018-06-14 at 16 16 27" src="https://user-images.githubusercontent.com/3685671/41414327-60891586-6fee-11e8-8064-27d9819141cc.png">

**Comment by danielmartinprieto** [comment]
Hey, @ranhsd. I don't see anything weird in your code, just make sure your `MovieListViewState` struct is indeed conforming to `Equatable` and that you're using the latest version of ReSwift (when in doubt, check using `master`).

This `store.subscribe(self) { $0.select(MovieListViewState.init) }` is the way I implement my subscriptions as well and it works ok for me (without having to call `skipRepeats`).

**Comment by ranhsd** [comment]
Hi @danielmartinprieto 

this is the MoveListViewState:

```
struct MovieListViewState : Equatable {
    let movies: [Movie]
    let searchBarText: String
    let searchBarShowsCancel: Bool
    let searchBarFirstResponder: Bool

    init(_ state: MainState) {
        
        print("init")
        
        movies = state.movies

        switch state.search {
        case .canceled:
            searchBarText = ""
            searchBarShowsCancel = false
            searchBarFirstResponder = false
        case .ready:
            searchBarText = ""
            searchBarShowsCancel = true
            searchBarFirstResponder = true
        case .searching(let text):
            searchBarText = text
            searchBarShowsCancel = true
            searchBarFirstResponder = true

        }
    }
```
And the Podfile is: 

```
# Redux pods
  pod 'ReSwift', :git => 'https://github.com/ReSwift/ReSwift.git'
```

And I still get the syntax error

Thanks!

**Comment by danielmartinprieto** [comment]
Sorry, I was talking about your original code and the fact that your subscription was getting called even though that part of the state hasn't changed.

**Comment by DivineDominion** [comment]
Can you figure out why the code doesn't compile? I think it was because it should be 2 underscores nowadays; try this:

```
mainStore.subscribe(self, transform: {
    $0.skip(when: { _, _ in true }).select(MovieListViewState.init)
})
```

**Comment by ranhsd** [comment]
Hi @DivineDominion now it is complied but the MoveListViewState init called only one time and it should be called multiple times (for every change but not for every dispatch of an action)

**Comment by DivineDominion** [comment]
Yeah sure, the above code _always_ skips. Now we know there's something fishy with your equatability.

**Comment by ranhsd** [comment]
Hi @DivineDominion. Actually it's not my code. What I can do is to try to integrate the same solution in one of my ReSwift projects there I know exactly how it should behave.

**Comment by affbedran** [comment]
Any updates to this? @ranhsd

**Comment by ranhsd** [comment]
Hi @affbedran 
I finally gave up on this approach and what I did is to create the view model inside the newState of ReSwift like this: 

```
func newState(state: MyState) {
   let viewModel = MyViewModel(state: state)
  ... 
}
```

With this approach I can use skipRepeats without any problem... 

Ran.
