### ISSUE TITLE
"Unable to infer closure type in the current context" in subscription closure

### ISSUE THREAD

**Issue by grigorryev** [ReSwift/ReSwift#358]
Hi, I'm trying to subscribe view controller to application sub-state and receiving the error:

![image](https://user-images.githubusercontent.com/21245681/41362010-03006c62-6f39-11e8-9aa5-9f9c592dee0a.png)

What am I doing wrong?

**Comment by mjarvis** [comment]
When you use `select`, you need to change your `newState` function's parameter type to match the type returned from `select`.
So, if `state.repositories` is of type `[Repository]`, then you need to have `func newState(state: [Repository])` instead of `func newState(state: AppState)`

**Comment by grigorryev** [comment]
Cool, thank you!
Quite an educative issue, didn't expect to find the problem in another method.
