### ISSUE TITLE
Can ReSwift be used for utility functions?

### ISSUE THREAD

**Issue by coderMemberam** [ReSwift/ReSwift#363]
ReSwift should be used only for logic associated to views?

I have a **use case** where i need a common function to create dictionary from large data coming from web service. i have a need to use this dictionary across pages for validations!!
I prefere to create action for this to use across app.

**Is this approach valid as there is no need to update view in this case.**

My plan is to trigger action and store dictionary locally to page and use it when ever required.

**Comment by mjarvis** [comment]
Yes, ReSwift can be used for state thats not directly used for views.
Dispatching an action & adding that data set to the state is a great way to have that data available across your application, even if it doesn't need to update a view when its added.
Subscription selections & skips will ensure that adding it doesn't affect existing subscriptions.
