### ISSUE TITLE
Building ReSwift as a dependency using Carthage

### ISSUE THREAD

**Issue by sejersbol** [ReSwift/ReSwift#373]
Hi,

I'm trying to build ReSwift using:

`$ carthage update --platform iOS --no-use-binaries`

But I keep getting:

`Failed to write to /Users/XXX/Developer/Projects/XXX/Carthage/Build/iOS/ReSwift.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “ReSwift.framework” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/XXX/Library/Developer/Xcode/DerivedData/ReSwift-bmuzndysbkjrnnchodupxilcxzgk/Build/Products/Release-iphoneos/ReSwift.framework, NSUnderlyingError=0x7fc187f23b00 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

If I clone ReSwift and build from Xcode I can build the ReSwift.framework for both the simulator (i386) and real devices (arm). Any idé as to what is wrong? (the build log does not give me a clue...)

**Comment by DivineDominion** [comment]
Which Xcode version are you using?

**Comment by sejersbol** [comment]
Yeah, that's probably the issue. I'm trying to build using Xcode 10/Swift 4.2... But there is no issues when building ReSwift from within Xcode (10.0). Any ideas?

**Comment by DivineDominion** [comment]
I have zero trust in the Xcode 10.0 build tools at the moment because a lot of things don't compile in one scenario (`swift build` from command line) while they do build from Xcode, and vice versa.

**Comment by sejersbol** [comment]
Hopefully the build tools will get fixed. Guess I will make a fat library then (lipo it together)...

**Comment by sejersbol** [comment]
FYI, here is my script https://github.com/sejersbol/ReSwift/blob/master/build_universal_static_library.sh

**Comment by DivineDominion** [comment]
Thanks for sharing! Do you apply signing later in the app?

**Comment by sejersbol** [comment]
Yes :-)
