### ISSUE TITLE
Tagged Versions for ReSwift, ReSwift-Router

### ISSUE THREAD

**Issue by jjgp** [ReSwift/ReSwift#375]
There have been many changes landed to master since the last tagged version. In addition, ReSwift-Router is behind the latest ReSwift. i.e. a Cartfile such as the following would fail to compile...

github "ReSwift/ReSwift" "master"
github "ReSwift/ReSwift-Router" "master"

Is there a process to tag releases, may we bump the versions? Cheers,

**Comment by DivineDominion** [comment]
We should pin the ReSwift dependency in ReSwift-Router to one that does compile at the moment. Could you create a PR in the Router repo that references a ReSwift version you found to be useful? Starting somewhere should help get the ball rolling.

Or do you want to propose specific commits to be tagged? We could do that, too, for old commits if it provides benefit, I guess.

**Comment by jjgp** [comment]
ReSwift Router is tagged to the last release of ReSwift 4.0.1. I was curious when the release plan for ReSwift so that the Router can then bumped to use some of the changes that have landed to this master. I just found the Projects / Release 4.1.0 plan which answers this. Once 4.1.0 lands we can bump then. I'll close this for now. Thanks!
