### ISSUE TITLE
Use ReSwift in modular app

### ISSUE THREAD

**Issue by ranhsd** [ReSwift/ReSwift#377]
Hi, I have some question about using ReSwift and REDUX pattern in modular app. 

Modular app is one applications which divided into frameworks. An example to framework can be: 

- Core Framework - contains core capabilities which are shared in the app (like: security, user defaults and more)

- Network Framework - contains all the network requests 

- UI Frameworks - to share and reuse UI components inside the app like: Buttons, TextFields, Table views and more. 

The major part in each modular app is the **Feature Frameworks** which are a code for specific feature inside the big app. Such features can be: HomeFeature, ProfileFeature, SettingsFeature, FeedFeature and more and more according to the app capabilities. **Each feature should not be depend on other feature.**

The question is how ReSwift can be used in such architecture? The challenge is how to share the state (which should be global) between the Feature framework. 
Let's say that we create the AppState on the App level (in the app delegate) and the app is depended on all the Feature framework. Inside each feature framework we will create the specific redux components for this specific feature (e.g. in HomeFeature we will have HomeState, HomeReducer and HomeActions which are relevant only to this feature). 

Now, in such architecture the App knows the HomeState and HomeReducer because they are exposed by the Feature framework and we have dependency but the problem is that the Feature framework is not depended on the App and the feature framework don't **know** what is an AppState or what is a Store so we cannot dispatch actions in it. 

I hope that my what I describe above is clear... and would like to hear your thoughts about it.
I think ReSwift is a great and very powerful library and if we will be able to create a modular app and still utilize this pattern it will be awesome!

Thanks.

**Comment by manmal** [comment]
@ranhsd I haven't fully thought it through, but could you put the Store into its own module, and all feature modules import it? Actions and Reducers could live in the feature modules.

**Comment by ranhsd** [comment]
Hi @manmal
Thanks for your response.
I can do that but the store is depended on the app state which is part of the App. And I cannot create dependency to the app from the redux store module.

**Comment by mjarvis** [comment]
@ranhsd Hi Ran! I have a similar setup to what you're describing working by using generics.
Here is an example oh how one could separate a feature out such that it has no knowledge of the app itself:

AccountsFeature.framework:
```swift
import ReSwift
import UIKit

public struct Account {}

public struct AddAccount: Action {
    public let account: Account
}

public protocol HasAccounts {
    var accounts: [Account] { get }
}

public func accountsReducer(action: Action, state: [Account]?) -> [Account] {
    var state = state ?? []
    switch action {
    case let action as AddAccount:
        state.append(account)
    default:
        break
    }
    return state
}

public final class AccountsViewController<S: StoreType>: UIViewController where S.State: HasAccounts {
    private let store: S
    
    public init(store: S) {
        self.store = store
        super.init(nibName: nil, bundle: nil)
        // ...
    }
}
```

Main.app:
```swift
import AccountsFeature
import ReSwift
import Foundation

struct AppState: StateType {
    var accounts: [Account]
}

extension AppState: HasAccounts {}

func appReducer(action: Action, state: AppState?) -> AppState {
    return AppState(
        accounts: accountsReducer(action: action, state: state?.accounts)
    )
}

let store = Store<AppState>(reducer: appReducer, state: nil)

let controller = AccountsViewController(store: store)
```

**Comment by ranhsd** [comment]
@manmal No it won't because then the app will not know the state and I cannot create dependency between them because I need to avoid circular dependencies. 

@mjarvis  Your solution looks good, actually it looks very good. What I did so far is I use DispatchFunction instance instead of StoreType (which BTW is new to me :)) and I did it without generics. So my code looks like the following: 

**My Feed Feature**

```
public class FeedViewController: UIViewController {
    
    var networkManager: TFNetwork!
    open var dispatchFunction: DispatchFunction!

    @IBOutlet weak var collectionView: UICollectionView! {
        didSet {
            collectionView.backgroundColor = .white
        }
    }
    
    public static func makeViewController() -> FeedViewController {
        let storyboard = SwinjectStoryboard.create(name: "Feed", bundle: Bundle(for: self),container: container)
        let viewController = storyboard.instantiateViewController(ofType: FeedViewController.self)
        return viewController
    }
    
    public override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationItem.title = NSLocalizedString("FEED_TITLE", comment: "")
        self.observe(theme: \TFAppTheme.custom.feed)
        
        dispatchFunction(FeedAction())
        
    }
}
```

And in my main app I use dependency injection (using Swinject):

```
            let vc = FeedViewController.makeViewController()
            
            vc.tabBarItem = r.resolve(UITabBarItem.self, arguments: UIImage(named: "tab_feed"), UIImage(named: "tab_feed_active"), 0)
            
            vc.dispatchFunction = store.dispatchFunction
        
            let nc = UINavigationController(rootViewController: vc)
            return [nc]
```

I think your solution looks better (although it use generic). What do you think? 

Thanks!

**Comment by mjarvis** [comment]
@ranhsd The advantage with my solution is that it can be used for subscribing to the store, as well, as opposed to just dispatching actions.

```swift
public final class AccountsViewController<S: StoreType>: UIViewController where S.State: HasAccounts {
    private let store: S
    
    public init(store: S) {
        self.store = store
        super.init(nibName: nil, bundle: nil)
        // ...
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        store.subscribe(self) { 
            $0.select { $0.accounts }
        }
    }
}

extension AccountsViewController: StoreSubscriber {
    func newState(state: [Account]) {
        // ...
    }
}
```

As for the injection types & storyboard initialization you can still use the generics with that, its just a bit more awkward because you have to manually specify the generic argument instead of it being inferred by the init function.

(Aside: there is also `DispatchingStoreType` for a store that can only dispatch, if you prefer that instead of passing around the dispatch function itself)

**Comment by ranhsd** [comment]
Hi @mjarvis I found some issues (that maybe you will know how to resolve) using it: 

1. You cannot use storyboards - because the view controller use generics, initialization from storyboard will not work in runtime. I assume that your are not using storyboard in your project ... 

2. How to use action creators in such architecture? Action creators expect to receive the AppState and store and our module don't have access to the AppState

3. Let's assume that I want to subscribe to more than one sub-state in the framework. Did you had the chance the face such requirement?

Thanks!

**Comment by mjarvis** [comment]
1. Correct, you cannot use storyboards directly using the generic method. You can however nest a non-generic view controller for the storyboard load inside of a generic one. (IE have the storyboard vc be a child view controller)

2. Action creators can be created using generics & protocols as well:
```swift
func doubleValueActionCreator<T: HasTestValue>(state: T, store: Store<T>) -> Action? {
    return SetValueAction(state.testValue! * 2)
}
store.dispatch(doubleValueActionCreator)
```

3. The controller's generic restrictions can be extended to include many sub-states:
```swift
where S.State: HasAccounts & HasTestValue & HasOtherThings
```
or the protocol itself can have more than a single item in it. (My cases use a single sub-state per protocol to allow for composing and re-use across components)

**Comment by ranhsd** [comment]
Hi @mjarvis Thanks,

I go step by step according to what you described.  My action creator need to get parameters also so what I did is to create the following action creator: 

```
public func loadFeedActionCreator<S : HasFeedState>(networkManager: TFNetwork) -> (S, Store<S>) -> Action? {
    
    return {state, store in
        return nil
    }

}
```

The problem is when I am trying to dispatch this action I get the following error: 

![image](https://user-images.githubusercontent.com/3685671/47809433-8051dd80-dd49-11e8-8f08-8225defcb673.png)

I really don't know why I am getting it here... I am familiar with this error but it looks like that the store is ok. Do you know why I am getting it?  (P.S. it is not related to the networkManager parameter)

**Comment by mjarvis** [comment]
I'm not sure how to get around this error... I can reproduce it as well. Seems to be something about returning a generic function.

Somewhat related -- There is a plan in place to deprecate `ActionCreator` and `AsyncActionCreator` in favour of Thunk middleware, which can be used in a manner which avoids this error.

**Comment by ranhsd** [comment]
Yes.. that's totally strange... I am trying to check why its not working ...

**Comment by ranhsd** [comment]
Hi @mjarvis It looks like only this code is working for now: 

```
struct someAction : Action {
    
    let networkManager: TFNetwork
    
    init(networkManager: TFNetwork) {
        self.networkManager = networkManager
        performAction()
    }
    
    private func performAction() {
        
    }
}
```

and in the view controller: 

```
store.dispatch(someAction(networkManager: networkManager))
```

I don't like it so much but maybe it can be an intermediate solution until the Thunk will be available.

**Comment by mjarvis** [comment]
@ranhsd `Thunk` is something you can use now if you want, its just a piece of middleware and an action, you can add them to your project without any modifications to ReSwift itself -- https://github.com/ReSwift/ReSwift/blob/b7b3f6cbc64252fc845253963ca896a0adbeb3c8/ReSwift/CoreTypes/Thunk.swift

**Comment by ranhsd** [comment]
Hi @mjarvis ... ok I am trying to integrate it now... 

BTW.. did you had a chance to look on this one:  
https://github.com/jordanebelanger/ReSwiftSaga

**Comment by ranhsd** [comment]
Hi , I managed to do something with Thunk. 
I had the same error like the one that returned by the Action Creator and then I changed it a bit and come up with the following: 

```
func loadFeed<S : HasFeedState>(manager: TFNetwork, state: S) -> Thunk<S> {
    return Thunk(body: {dispatch, getState in
        print("action executed")
    })
}
```
 
You must use  

`<S : HasFeedState>`

because by when you create the thunk middleware you create it with the AppState and the middleware perform a **switch** condition to know if the action should be handled or not, and because the AppState conform to the HasFeedState protocol the action runs. 
Another important thing to notice is that **you must**  end the state as a parameter to the thunk action function otherwise you will get the **Generic parameter S cannot be infer** error. 
now the value of the state that you send is actually the state that you have in your store so in your view controller you should call it like this: 


`
store.dispatch(loadFeed(manager: networkManager, state: store.state))
`

**Comment by mjarvis** [comment]
@DivineDominion Thats exactly the approach I use. My examples were just the more specific parts of defining the features themselves, and being able to pass the store around without knowing about `AppState`

**Comment by ranhsd** [comment]
Hi @DivineDominion this is also how I built it. I have more target frameworks for different parts in my app like: networking, ui components and more but the idea is that each module will provide its own resources and I am  not count on a some central place. To be honest, it is much more complicated to be achieved in ReSwift comparing to other approaches like: MVVM, VIPER or Clean Swift but I am not going to give up on that because I really think that it worth it. 
Another challenging topic is routing. Do you use ReSwift-Router for performing routing between your features modules or you use another approaches (like: flow coordinators etc.)?

**Comment by ranhsd** [comment]
Hi @mjarvis What do you think about Routing in such app? I want to use ReSwift-Router for routing between view controllers in the app but I still want to decouple one feature from other features. I am starting to think that Routing should be implemented centrally without creating Routable implementation inside each module. So the app will define all the routes on the app level and we will pass the **HasNavigationState** to each module so we will be able to dispatch routing action inside the module but the route will be handled centrally by the app (where it has access to all the feature modules). 
What do you think? there is a way that the feature module will provide the routing object to the app or it should be handled centrally? 

Thanks.

**Comment by mjarvis** [comment]
I highly recommend that routing happens at the app level.
My method of doing this is by having a piece of middleware be the coordinator, which pushes / pops / presents appropriate controllers when certain actions are dispatched.

ReSwift-Router is not production ready at this time, I do not recommend using it except for experimentation & learning. (We'd love to rebuild it in a more modular and production ready way, but routing is *HARD* and so far no-one has come up with a good general solution)

**Comment by mjarvis** [comment]
@ranhsd I do not use stored route state, I find maintaining that state extremely difficult, and then it requires a distinct "route action" as you call it. Instead, I use actions that don't know anything about routing, and its all handled in my middleware.

For example, my middleware watches for `AccountsFeature.AccountSelected` action, and accordingly creates a `ProfileViewController` and pushes it onto the navigation stack (which it owns).

This way, there is zero direct connection between the object dispatching the action, the router, and the next controller displayed. Same goes for canceling / returning etc. all dispatched as a normal action, and intercepted by the middleware to do the appropriate navigation.

**Comment by ranhsd** [comment]
Hi @mjarvis Got it! 

Thanks!
