### ISSUE TITLE
Please publish a new Carthage binary for swift 4.2

### ISSUE THREAD

**Issue by drkibitz** [ReSwift/ReSwift#382]
This library is the only one that needs to build from source, and I'm hitting a major bug with Carthage and Xcode 10.1 (the current arch x86_64 problem). This won't fix the root cause, but it will help me, as well as speed up my builds a little as well ;)

**Comment by danielmartinprieto** [comment]
Hi, @drkibitz. Could you elaborate a bit more what’s exactly your problem?

If Carthage finds a non compatible binary, it will build it from source by itself, and this process takes very little time for a framework like this.

Once you have the .framework, your don’t need to go though that process anymore unless a new version is release, so your builds should take the same time.

I didn’t have any problem using the master branch to pull the dependency using Xcode 10 and Swift 4.2., but maybe I’m missing something?

Thanks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by drkibitz** [comment]
I understand, I just don't like having any dependencies pinned to master as it will always build from source, and right now building from source is a pain because of this bug https://github.com/Carthage/Carthage/issues/2613

Which is the problem I was referring. I also found a workaround as you can see as the final comment of that bug. This issue was just that there hasn't been a release in a bit, and out of all my dependencies, ReSwift was the only thing that actually needed to build from source because the latest binary is for swift 3 only.

**Comment by DivineDominion** [comment]
There's a v4.1.0 milestone and we're working on it :)
https://github.com/ReSwift/ReSwift/milestone/3
