### ISSUE TITLE
Possible `automaticallySkipsRepeats` regression on `master`

### ISSUE THREAD

**Issue by peter-tomaselli** [ReSwift/ReSwift#394]
According to [this comment](https://github.com/ReSwift/ReSwift/issues/303#issuecomment-461656238), there is some problem with `automaticallySkipsRepeats` not actually functioning correctly for simple `Equatable` states on the `master` branch, as compared to the `4.0.1` release.

I tried to reproduce this problem myself with some simple unit tests — in the style of `AutomaticallySkipRepeatsTests.swift` — but was unable to do so. I’m assuming that’s because this is either not a problem anymore, was perhaps never really a problem, or most likely, more detail is needed to reproduce the original bug report.

I was encouraged to file an issue here anyway 😄 because I was told that the possibility of this bug was blocking the release of [`4.1.0`](https://github.com/ReSwift/ReSwift/milestone/3), which my team would love to see released. (Specifically, we’d really like to have a Swift-4.2-compatible release tag to pin our dependencies to, instead of having to use `master`).

If there’s anything else I can do to help track down this bug, or to facilitate a new release in general, please let me know. Thank you!!

**Comment by mjarvis** [comment]
@sjmueller This ticket is in regards to your comments.

To note: @DivineDominion made an incorrect statement regarding the default value for `automaticallySkipsRepeats`. The commit that the linked to correctly shows the default value is `true`. And can also be confirmed by looking at current master: https://github.com/ReSwift/ReSwift/blob/master/ReSwift/CoreTypes/Store.swift#L60

I am also unable to reproduce this issue. I attempted to reproduce by adding the following test:

```swift
    func testSkipsStateUpdatesForEquatableSubStateByDefault() {
        let reducer = TestValueStringReducer()
        let state = TestStringAppState()
        let store = Store(reducer: reducer.handleAction, state: state, middleware: [])
        let subscriber = TestFilteredSubscriber<String>()

        store.subscribe(subscriber) {
            $0.select { $0.testValue }
        }

        XCTAssertEqual(subscriber.receivedValue, "Initial")

        store.dispatch(SetValueStringAction("Initial"))

        XCTAssertEqual(subscriber.receivedValue, "Initial")
        XCTAssertEqual(subscriber.newStateCallCount, 1)
    }
```

This test passes on current master. If the skip was not occurring the last line would fail, which can be confirmed by setting `automaticallySkipsRepeats: false` on the store in the test.

**Comment by mjarvis** [comment]
To follow up from the above linked PR, the reproduction case for this is when the root state is *not* `Equatable`, but the selected substate is.
Subscriber Test reproduction:
```swift
    func testSkipsUpdatesForEquatableSubStateByDefault() {
        let reducer = TestNonEquatableReducer()
        let state = TestNonEquatable()
        let store = Store(reducer: reducer.handleAction, state: state)
        let subscriber = TestFilteredSubscriber<String>()

        store.subscribe(subscriber) {
            $0.select { $0.testValue.testValue }
        }

        XCTAssertEqual(subscriber.receivedValue, "Initial")

        store.dispatch(SetValueStringAction("Initial"))

        XCTAssertEqual(subscriber.receivedValue, "Initial")
        XCTAssertEqual(subscriber.newStateCallCount, 1)
    }
```

**Comment by mjarvis** [comment]
The fix for this has been deployed in https://github.com/ReSwift/ReSwift/releases/tag/4.1.1

**Comment by sjmueller** [comment]
Apologies @mjarvis for being late to the thread (startup life can get crazy), but glad you were able to reproduce and issue a fix!
