### ISSUE TITLE
Should we crash when cast to subscriber-specific state fails?

### ISSUE THREAD

**Issue by Ben-G** [ReSwift/ReSwift#4]
Subscribers can request a specific sate type, by changing the method signature of the `newState` method, e.g.:

``` swift
    func newState(state: HasAuthenicationState) {
        loggedInLabel.text = "\(state.authenticationState.userAuthenticated)"
    }
```

This is very useful as it allows us to restrict access to only the relevant sub-state and it empowers extensions such as `SwiftRouter` that can see the app state through the lense of a particular protocol that they define themselves.

If the state cannot be casted this currently fails silently, we should consider crashing with `fatalError` since this should never occur unexpectedly after shipping an app, but would be useful during development.

**Comment by raheelahmad** [comment]
Would `assert` be better as it gets stripped out conditionally with a build setting?

**Comment by Ben-G** [comment]
Yes @raheelahmad! If we go ahead with this we should use an `assert` for the before-mentioned reasons :)
