### ISSUE TITLE
Module cannot be imported by the Swift 5.0 compiler

### ISSUE THREAD

**Issue by Rawnly** [ReSwift/ReSwift#402]
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler: `path-to-the-project/Carthage/Build/iOS/ReSwift.framework/Modules/ReSwift.swiftmodule/arm64.swiftmodule`

What can I do? I've also setted 4.2 as `Language Version` in my `Build Settings`

**Comment by mjarvis** [comment]
@Rawnly The Carthage binary is compiled using Xcode 10.1 as it was released when 10.2 was still in beta. You'll need to `--no-use-binary` with Carthage in order to get a Swift 5.0 or 4.2.2 compatible binary.
