### ISSUE TITLE
jQuery in Docs/jazzy-theme uses old and vulnerable version

### ISSUE THREAD

**Issue by jpstotz** [ReSwift/ReSwift#407]
The ReSwift project uses and old and vulnerable version of jQuery: 1.11.1
https://github.com/ReSwift/ReSwift/blob/master/Docs/jazzy-theme/assets/js/jquery.min.js

This file seems to be copied from one of the default jazzy themes, however in jazzy all `jquery.min.js` files have already been replaced by a newer version.

In general using a vulnerable version in the documentation is no big deal, however under certain conditions the docs folder and therefore the vulnerable jQuery version can get included into an iOS app and therefore it might even be used by the app.

Therefore can someone please update this file to the latest jQuery version?

**Comment by DivineDominion** [comment]
Thanks for pointing this out, @jpstotz !
