### ISSUE TITLE
Dispatching Action from inside Middleware?

### ISSUE THREAD

**Issue by ciathyza** [ReSwift/ReSwift#408]
I have a scenario where I use a middleware to distinguish between different actions and depending on the action the MW modifies the action's data and then dispatches a different action with the data.

The problem I'm facing is that I expect the middleware to be executed again for the newly dispatched action from inside it but it's not executed.

An example:

I have two actions: ActionA, ActionB. In my middleware I use a switch conditional with cast as to figure out what action goes through the middleware. If it's ActionB it will be intercepted, its data modified and then I dispatch a new ActionA with the modified data from within the middleware. The new ActionA should then go through the middleware again (and be processed differently) but it's not happening.

Is this possible? Or is this kind of approach sub-optimal?

**Comment by danielmartinprieto** [comment]
This is something normal and should work as you describe. Could you share the middleware's code so we can help you debug the issue?

**Comment by ciathyza** [comment]
Hi Daniel! I checked once more closer now and realized that this works indeed. The issue I'm having seems to be related to ReSwiftRouter which I'm using and trying to modify to support pushing/popping single route segments to its route. The ReSwiftRouter doesn't seem to get notified whenever the second action (ActionA) is dispatched by the middleware.

**Comment by danielmartinprieto** [comment]
All right, I'm glad it worked!
