### ISSUE TITLE
Use with design patterns such as VIPER / MVP?

### ISSUE THREAD

**Issue by nodediggity** [ReSwift/ReSwift#431]
I'd be interested to see how people are using ReSwift with patterns such as VIPER and MVP.

I have an app using VIPER I'd be super keen to integrate with ReSwift, I'm a little thrown off by this however -

```swift
    override func viewWillAppear(_ animated: Bool) {
        mainStore.subscribe(self)
    }

    override func viewWillDisappear(_ animated: Bool) {
        mainStore.unsubscribe(self)
    }
```

I'm thinking the principles of VIPER mean dispatching of actions would more than likely live in an `Interactor` and the `Presenter` would perhaps be the `StoreSubscriber`. 

![bpM7t](https://user-images.githubusercontent.com/25435000/69337380-a00bba80-0c58-11ea-9f27-dac21e75f643.png)

However to setup the store subscriptions I need to trigger the `un/subscribe` calls from view controller lifecycle methods.

One approach I'm considering is simply have something in my viewcontroller that notifies the presenter of `viewWillAppear` and `viewWillDisappear`.

This can be a simple method call on the presenter, meaning the view still has no concept of the store layer, which _should_ still adhere to the principles.

 I already do this with `viewDidLoad` to trigger an initial data fetch, in the case of feed for example.

Has anyone else tackled this? 

Would love to hear your thoughts 👍

**Comment by nodediggity** [comment]
Actually the more I think on this now, unless you have a global `Store` the `Presenter` would be then interacting with a service, just by subscribing. 

Perhaps everything should live in the `Interactor` and the `Presenter` be updated of state changes in much the same way it'd be notified of service changes, such as an api response?

**Comment by danielmartinprieto** [comment]
If you want to do this, then you're right about your second comment: the store should live within the Interactor. I would say the store is an interactor itself. Which leads me to my real suggestion.

ReSwift/Redux already gives you a fair amount of indirection and boilerplate, which comes with certain tradeoffs. Note that you'll have: store, middleware, reducers, actions, selectors... apart from the ones that come with VIPER (also a lot of them).

Both paradigms try to do the same thing: separation of concerns, easier testing, decoupling... and mixing the two together would be too confusing and necessary.

I advise you to pick one and don't mix both of them.
