### ISSUE TITLE
Crash on launch when using latest on Swift Package Manager

### ISSUE THREAD

**Issue by nodediggity** [ReSwift/ReSwift#432]
I'm seeing a crash when calling `store.subscribe(self)` using the latest package via Swift Package Manager.

<img width="682" alt="Screenshot 2019-12-03 at 20 37 51" src="https://user-images.githubusercontent.com/25435000/70087747-ce03de00-160c-11ea-87f4-48d9cec1115c.png">

Attached is a bare bones project that reproduces the error.

It seems to land on -

```
#1	0x0000000102b5d91f in Store.init(reducer:state:middleware:automaticallySkipsRepeats:) 
at /Users/nodediggity/Library/Developer/Xcode/DerivedData/ReSwiftExample-czegixqbdykoeuftxdzkpeylbnfn/SourcePackages/checkouts/ReSwift/ReSwift/CoreTypes/Store.swift:82
```

<img width="1354" alt="Screenshot 2019-12-03 at 20 40 53" src="https://user-images.githubusercontent.com/25435000/70087981-3d79cd80-160d-11ea-9f0f-6058232c95b8.png">

I'm running Xcode Version 11.2.1 (11B500)

You should be able to reproduce the crash simply by building the attached project

[ReSwiftExample.zip](https://github.com/ReSwift/ReSwift/files/3918600/ReSwiftExample.zip)

**Comment by nodediggity** [comment]
I suspect this may be related to https://bugs.swift.org/plugins/servlet/mobile#issue/SR-11564 - feel free to close if so 👍

**Comment by liuwin7** [comment]
The same issue occurred to me last night. I make the same project with the cocoapods and it works fine. So I think it maybe a xcode bug.

**Comment by lucagiorgettispotsoftware** [comment]
The same issue occurred to me. With XCode 11.0 it works fine.

**Comment by lintmachine** [comment]
I'm investigating a similar issue in our project, but the attached example builds and runs for me without crashing with Xcode 11.6.
