### ISSUE TITLE
StateType vs Hashable

### ISSUE THREAD

**Issue by Elshad** [ReSwift/ReSwift#438]
After one year of using ReSwift i find that, i don't properly understand why we need `StateType` and i have dumb questions, sorry for this :)

What is difference between `StateType` and `Hashable` for ReSwift? Can ReSwift catch changes of state when i will use only `Hashable`?

**Comment by DivineDominion** [comment]
@Elshad It's, in fact, used as a generic constraint without any functionality. You don't even need `Hashable` or `Equatable`. I do think one could refactor the type away with the modern Swift generics and protocol extensions and instead go for `Store<T>` and such without any further constraints. If you're game for this, you're welcome to start a PR with a proposal so we can all see what happens in practice!
