### ISSUE TITLE
Question: Thread safety

### ISSUE THREAD

**Issue by jonah-neugass-ck** [ReSwift/ReSwift#439]
My app is crashing with this error:

Fatal error: ReSwift:ConcurrentMutationError- Action has been dispatched while a previous action is action is being processed. A reducer is dispatching an action, or ReSwift is used in a concurrent context (e.g. from multiple threads).: file /Users/jonah.neugass/Mobile/CKCanada/Carthage/Checkouts/ReSwift/ReSwift/CoreTypes/Store.swift, line 154

Should I be dispatching all my actions on the main thread or should I make my own queue and dispatch the actions there?

**Comment by DivineDominion** [comment]
I'd generally start with main queue access, especially if you want to have an easier time updating the UI, but if you wrap everything in a background queue, that can work as well.

**Comment by jonah-neugass-ck** [comment]
Great, thanks! Any plans on making ReSwift thread safe?

**Comment by mjarvis** [comment]
@jonah-neugass-ck ReSwift is thread safe, however, it is not concurrent access safe.
The only requirement is all actions need to be dispatched synchronously. The easiest way to achieve this is to have dispatching happen on a single thread, which is commonly, but does not need to be, the main thread.

There is no plan to make ReSwift safe for concurrent action dispatching. You can quite easily to so yourself with a small wrapper around a `Store` instance that dispatches all actions on a single queue. If this is a background queue, you'll also need to dispatch out to the main queue when you receive subscription updates to update UI.
