### ISSUE TITLE
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0

### ISSUE THREAD

**Issue by gooson** [ReSwift/ReSwift#448]
**Environment**
Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

Xcode Version: 12.0
Swift Version: 5.3
Installation Platform & Verison: Swift Package Manager 7.1.1

**Goals**
What do you want to achieve?

Remove warnings at compile time

**Expected Results**
What do you expect to happen?

I hope you can update your library

**Actual Results**
What actually happened? Can you provide a stack trace?

The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

<img width="299" alt="스크린샷 2020-09-28 오전 2 15 25" src="https://user-images.githubusercontent.com/1947069/94371304-7c46ba00-0130-11eb-8754-466354c3cc42.png">

**Comment by rickypowell** [comment]
Are you sure this is not a CocoaPods issue? I've had a similar warning come up in my project and it was resolved with a modification to the the pods file.

**Comment by gooson** [comment]
@rickypowell 

I don't use CocoaPods. 
I am using Swift Package Manager. 
Other libraries are responding to the issue through the latest updates.

IPHONEOS_DEPLOYMENT_TARGET = 9.0;
https://github.com/danielgindi/Charts/commit/e98681cc26aac6185ad73330a6e22b0e97a5b302

I think it will be solved by modifying the file below.

<img width="520" alt="스크린샷 2020-09-28 오전 2 40 41" src="https://user-images.githubusercontent.com/1947069/94371801-21af5d00-0134-11eb-9989-ca65e4c413b1.png">

**Comment by mjarvis** [comment]
This warning is showing up because as of the current release, we still support iOS 8.0 as a valid target, by using an older version of Xcode.

We are committed to maintaining a sizeable amount of backwards compatibility, but understand this is pushing it a bit far.

I plan to do another assessment of minimum targets + swift versions before we do a 6.0.0 release (which already drops support for a number of Swift versions)

**Comment by mjarvis** [comment]
Resolved in https://github.com/ReSwift/ReSwift/releases/tag/6.0.0
