### ISSUE TITLE
Apps crashes for users with: closure #1 in variable initialization expression of static Assertions.swiftFatalErrorClosure

### ISSUE THREAD

**Issue by poonam-bhadikar** [ReSwift/ReSwift#458]
I am getting crashes logged on FireBase Crashlytics Dashboard for the app.
It says,
Fatal error: ReSwift:ConcurrentMutationError- Action has been dispatched while a previous action is action is being processed. A reducer is dispatching an action, or ReSwift is used in a concurrent context (e.g. from multiple threads).: file /Users/runner/work/1/s/Pods/ReSwift/ReSwift/CoreTypes/Store.swift, line 135

ReSwift pod version: 4.0.1

**Comment by DivineDominion** [comment]
Looks like you have a multi-threaded app that tries to call `store.dispatch` from various threads at once. You should dispatch actions only from one thread, e.g. the main thread.

Also, please upgrade to ReSwift 6.x for better concurrency handling.

**Comment by mjarvis** [comment]
Closing due to answer given and no response after 10 days.
