### ISSUE TITLE
StoreSubscriptionTests testDoesNotCaptureStrongly Fail when compiled for 'Release'

### ISSUE THREAD

**Issue by rase-rocks** [ReSwift/ReSwift#459]
Hi

When running the test target with a release scheme the `testDoesNotCaptureStrongly` test fails. _Speculation from a quick look at the code_ is that it appears that when compiled for release, Whole Module Optimisation enthusiastically removes the instantiation of the `TestSubscriber` altogether as it is only ever added to be subsequently nilled out again. It is this check that the `subscriber` was successfully added that fails, not the check that it is not retained. If that makes sense.

![Screenshot 2020-10-29 at 10 57 47](https://user-images.githubusercontent.com/38786434/97611159-b3e5a200-1a0d-11eb-8774-b76e78e4c83b.png)

Doing anything at all with the `TestSubscriber` after instantiation causes the test to pass. 

![Screenshot 2020-10-29 at 16 33 42](https://user-images.githubusercontent.com/38786434/97611287-e1325000-1a0d-11eb-9f4f-a1ef7ede727f.png)

A quick assertion `XCTAssertNotNil(subscriber)` is enough to stop WMO stripping out the instantiation. (I think, I have not delved that far into the Assembly). It is certainly enough to cause the test to pass.

Altering tests to make them pass is not something I would normally suggest! But, in this instance it appears that the code is correct and the test is 'at fault'. Also the part of the test that fails (actually adding the `subscriber`) is successfully tested elsewhere, verifying that `subscribers` do in fact get added.

If the consensus is that the above observations are correct I'm happy to put the 'fix' into a PR.

PS. Excellent work, great project!

**Comment by mjarvis** [comment]
Thanks. We don't often run the tests under release configuration but it is a good idea to have it passing.

It is interesting that `store.subscribe(subscriber!)` is insufficient for maintaining the subscription before the assertion.
I would be inclined to move the `XCTAssertNotNil` one line down so its after the count check, which makes more logical sense for the compiler maintaining the reference, vs it maybe optimizing the `= nil` up in the future.

**Comment by rase-rocks** [comment]
I suppose this is an example of just how much optimisation of code goes on by the compiler. I spotted it because I had a near miss once with 'debug' builds passing but the 'release' build optimisation caused an issue, never again!

I will swap the lines around and submit a PR.
