### ISSUE TITLE
Filter object in nested array and change value

### ISSUE THREAD

**Issue by billypap1** [ReSwift/ReSwift#469]
Hello, I have integrated ReSwift to my Swift App successfully , but I can't figure out how to filter object (id) in nested array.
For example, I have the following array:

var postsArray : [Post] = [ ... "different posts here..."]

struct Post {
  "bookmarked": "no",
  "id": "131313"
}

I want to change "bookmarked" field in specific id object inside postsArray. In JS we would have something like this: 
  
 case searchActions.BOOKMARK_POST:
                                return {
                                    ...state,
                                    postsArray: state.postsArray.map((post) =>
                                    post.id === action.postID ? {
                                            ...post,
                                            bookmarked: 'yes',
                                        } : post
                                    ),
                                }

How can I do this with ReSwift? Thank You.

**Comment by mjarvis** [comment]
@billypap1 This is more of a general swift question than ReSwift specific, but functional `map` exists in Swift as well.

An equivalent implementation could be something like:
```swift
postsArray: state.postsArray.map { post in 
  if post.id == action.postID {
    var post = post
    post.bookmarked = true
    return post
  } else {
    return post
  }
}
```

**Comment by billypap1** [comment]
Thanks for your response. I have tried it (in Reducer file) but I get errors  -> "not found postsArray", "closure expression is unused":

case let action as bookmarkPost:
postsArray: state.postsArray.map { post in 
  if post.id == action.postID {
    var post = post
    post.bookmarked = true
    return post
  } else {
    return post
  }
}
