### ISSUE TITLE
Migrate from Travis CI to GitHub Actions?

### ISSUE THREAD

**Issue by DivineDominion** [ReSwift/ReSwift#476]
Fixing Travis for 6.1.0 with Xcode 12.5 is getting a bit frustrating because the feedback loop is so slow.

- Example:  https://github.com/rosberry/texstyle/tree/master/.github/workflows
- Article: https://medium.com/rosberryapps/github-actions-ci-for-swift-projects-c129baceed1a

I don't see us exceeding the 2000 automation minutes anytime, soon, but the limitation does exist and could potentially slow down framework development.

What do y'all think? Pinging @mjarvis @dani-mp

**Comment by mjarvis** [comment]
I'm not against this. I think we're a bit overkill on the compatibility tree of CI builds so we can probably reduce our usage with a switchover.

**Comment by mjarvis** [comment]
Resolved by #486
