### ISSUE TITLE
Concurrency - protected reads

### ISSUE THREAD

**Issue by lukeredpath** [ReSwift/ReSwift#478]
I'm curious what ReSwift's policy on concurrency is - it seems like it has built-in protection from concurrent mutations with the use of the synchronised `isDispatching` property inside the main dispatch function so I'm wondering why it doesn't also have built-in protection from current state reads as well?

I think it's fine for ReSwift to have a policy of "this is not thread safe, only use the store on one thread" but in this case why have the dispatch lock at all?

Is there a case to be made for making the state a `Synchronised<State>` as well?

**Comment by lukeredpath** [comment]
I've opened up a PR - #479 - I understand if you don't want to accept this PR but as it was a relatively simple change to make and all of the tests passed I thought I'd open to see if people wanted to try it out.

**Comment by mjarvis** [comment]
The dispatch lock is simply for debugging help. To crash/error when the user attempts to dispatch from multiple queues rather than letting race conditions occur.
