### ISSUE TITLE
[question] where to draw the line with state

### ISSUE THREAD

**Issue by johnryan** [ReSwift/ReSwift#48]
I love this concept but I have some questions around where you envision the line being drawn with actions and state.

For instance, I know that in a UITabBarController example you override the default behavior and handle the event manually. How does something like this translate to a UISwitch? Is it overkill for this example and better to just receive the change and then post and action that the state of a switch changed?

Additionally there are lots of things in the UI realm, for instance scroll events on a tableview. In order to FULLY capture the state change these would be tracked but unless it is relevant to a given application this also seems like overkill.

Thoughts?

Thanks and great work!

**Comment by Ben-G** [comment]
We had a very similar question on another repo in this org: https://github.com/ReSwift/CounterExample-Navigation-TimeTravel/issues/1

Check it out and let me know if it answers your question :)

**Comment by johnryan** [comment]
Ha, that is almost exactly the same question. That answers most of my questions but i'd love to get your opinion something like a slider or a switch. 

For example you can register a selector to listen for when the slider is done changing, or a switch's value has changed. This could emit an action to update the store which in turn would emit a "store updated" event. 

For the case of the switch would the flow be like this: switch changed by user -> update store action -> store emits change -> view controller re-sets the switch with the same value it already has?

**Comment by Ben-G** [comment]
> For the case of the switch would the flow be like this: switch changed by user -> update store action -> store emits change -> view controller re-sets the switch with the same value it already has?

You will definitely run into a few cases where you need to force UIKit to work nicely with ReSwift. 
IMO what you suggest would be fine for the switch! Ideally you would stop the UIKit component from updating directly (e.g. like I do with UITabBarController, by setting up a delegate that doesn't allow the controller to update), but in many cases that won't be possible and there your proposed solution would be the way to go.

**Comment by johnryan** [comment]
Thanks for the advice! I look forward to seeing how this evolves.
