### ISSUE TITLE
What's a good way to cast results of a subscription in SwiftUI to a desired output type? 

### ISSUE THREAD

**Issue by alexwhb** [ReSwift/ReSwift#482]
So I might just have tunnel vision and can't see an obvious solution to this problem, but some help with this would be much appreciated. 

I have some state that I can either represent by a nil when not active or by a blank struct that implements a common protocol or maybe even a enum

example: 

```swift
protocol ActiveBookState {}
struct NoActiveBookState : ActiveBookState {}
struct ActiveBook: ActiveBookState {
    var some properties
}
```

Then in my app I use the subscriber paradime shown in #455. So In my view I do something like this:

```swift
@ObservedObject var activeBookState: Subscriber<ActiveBookState> = Subscriber(store)  { $0.select {$0.activeBookState } }
```

So I'm wondering if there's a way to cast that output to `ActiveBook` and skip any results that are not that type so as to not cause an exception? Or if this is a bad approach could someone point me in a better direction for how to handle this type of situation?  

in my SwiftUI I'm trying to something like this: 
```swift
 NavigationLink("Now Playing", destination: PlayerView(activeBook: activeBookState))
                        .navigationBarHidden(false)
                        .disabled(activeBookState.value is NoActiveBookState)
```

because this button is disabled when the sate is `NoActiveBookState` it should be impossible for the passed in 
Subscriber to ever be that state so we should be able to cast it to ActiveBook right?

**Comment by DivineDominion** [comment]
If `ActiveBookState` doesn't delare a lot of properties that all conforming types have to implement, and for which the protocol creates a useful abstraction, I'd start with an `enum` instead.

As for the subscription:

```swift
@ObservedObject var activeBookState: Subscriber<ActiveBookState> 
    = Subscriber(store)  { $0.select { $0.activeBookState } }
```

This looks fine if you're interested in the general type (or the enum itself.

For the binding, I'd introduce (derived) view model data:

    .disabled(activeBookStateIsActive)

and then

or, cheekily, in a private extension to your UI component for convenience:

```swift
extension TheSwiftUIView {
  fileprivate var activeBookStateIsActive: Bool { activeBookstate.value is ActiveBook }
}
```

----

With an enum, these things would flow a bit more naturally. I'm personally not a fan of boolean type checks. If that's used, it can probably also be modeled as a property of the receiving object instead, too, e.g.:

```swift
protocol ActiveBookState {
  var isActive: Bool { get }
}
struct NoActiveBookState : ActiveBookState {
    var isActive: Bool { false }
}
struct ActiveBook: ActiveBookState {
    var isActive: Bool { true }
    // other props
}
```

The type names and the property in combination sound super weird, though :) I'd try to come up with something else to be honest that expresses the different kinds better

**Comment by alexwhb** [comment]
@DivineDominion This is fantastic! Thank you so much for your comprehensive writeup. I'm going to try out your suggestions. I was leaning towards using an enum but was not sure if that was standard practice or not. I'm a bit new to Swift and iOS so excuse my ignorance. I typically live in Android land.

**Comment by DivineDominion** [comment]
@alexwhb Swift enums are pretty powerful but also weird at first. Your sample code's types looked similar to the `Result` or `Optional` type to me, so that's why I suggested using an enum. When a type hierarchy makes more sense, by all means use that :)
