### ISSUE TITLE
Change visibility of Store from 'open' to 'public final'?

### ISSUE THREAD

**Issue by DivineDominion** [ReSwift/ReSwift#492]
I was wondering what people override the default `Store` for.

Could we 'close' it make it a `public final class Store<State>`?

The ReSwift library itself compiles just fine with `public final`; the tests override subscription methods, so they require just `public`.

It might have consequences for 3rd parties, but I wouldn't know which kind.

What are all your thoughts on this?

**Comment by mjarvis** [comment]
The store is commonly overridden to provide reactive bindings, or to provide a thread-safe store. I would not recommend closing its access.

**Comment by DivineDominion** [comment]
Makes sense.
