### ISSUE TITLE
SIGSEGV on state.didSet

### ISSUE THREAD

**Issue by mhamann** [ReSwift/ReSwift#493]
In an app we recently released to the iOS App Store, we've started seeing the following crash within a couple seconds of opening the app and calling some `store.dispatch()` functions:

> Crashed: com.apple.main-thread
> SIGSEGV 0x0000000000000010

```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1f40 objc_msgSend + 32
1  libswiftCore.dylib             0x1cf6c8 __CocoaDictionary.Iterator.nextKey() + 100
2  libswiftCore.dylib             0x1cf8c0 protocol witness for IteratorProtocol.next() in conformance Set<A>.Iterator + 256
3  libswiftCore.dylib             0xd9364 Sequence.forEach(_:) + 632
4  App                            0x3e135c Store.state.didset + 4341896028 (<compiler-generated>:4341896028)
5  App                            0x3e1684 Store.state.setter + 20 (Store.swift:20)
6  App                            0x3e2770 Store._defaultDispatch(action:) + 173 (Store.swift:173)
7  App                            0x3e3c20 partial apply for closure #1 in Store.createDispatchFunction() + 4341906464 (<compiler-generated>:4341906464)
8  App                            0x3e3c68 partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed Action) -> (@out ()) + 4341906536 (<compiler-generated>:4341906536)
9  App                            0x3e3d58 partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed Action) -> () + 4341906776 (<compiler-generated>:4341906776)
10 App                            0x389660 partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed Action) -> (@out ()) + 4341536352 (<compiler-generated>:4341536352)
11 App                            0x3e5e5c closure #1 in closure #1 in closure #1 in createThunkMiddleware<A>() + 22 (createThunkMiddleware.swift:22)
12 App                            0x3897ac partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed Action) -> () + 4341536684 (<compiler-generated>:4341536684)
13 App                            0x3e3c68 partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed Action) -> (@out ()) + 4341906536 (<compiler-generated>:4341906536)
14 App                            0x3e3d58 partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed Action) -> () + 4341906776 (<compiler-generated>:4341906776)
15 App                            0x3e3c68 partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed Action) -> (@out ()) + 4341906536 (<compiler-generated>:4341906536)
16 App                            0x3e27d0 Store.dispatch(_:) + 4341901264 (<compiler-generated>:4341901264)
```

So far, we haven't been able to reproduce it locally, so I'm guessing it has to do with a race condition somewhere.

Any thoughts on what might be causing this or ideas on how to better debug it?

**Comment by DivineDominion** [comment]
Is there some other error code for a sub-category?

https://developer.apple.com/documentation/xcode/investigating-memory-access-crashes

Never had an iOS app crash tbh :)

Since you speak of race conditions: I do wonder if you do something odd around the use of `createThunkMiddleware`. I'd try to symbolicate the crash log first and inspect the call stack further.

**Comment by DivineDominion** [comment]
@mhamann Did you figure out a cause for this?

**Comment by mhamann** [comment]
Thanks for checking in @DivineDominion. I must've missed your original reply. We did solve this. We were using Combine within an Actor, and that seems to have been the trigger for this issue. Somehow, the Actor's subscription to the store was causing memory to be accessed in an unsafe way, and thus the sigsev crash.

My iOS dev knowledge isn't deep enough to know whether or not there is a good way to solve this, but we ended up moving the code from our Combine logic into ReSwift middleware. It ends up making the dispatch flow async, which is somewhat annoying, so other approaches might be better.

**Comment by DivineDominion** [comment]
@mhamann Great, then I'll close this issue!

For some async tasks, try out https://github.com/ReSwift/ReSwift-Thunk/ to dispatch an action that can perform something complex, access the state in the process, and dispatch actions to indicate progress. Like the HTTP request/pending/result triad.
