### ISSUE TITLE
Testing: Waiting for store.dispatch() to complete

### ISSUE THREAD

**Issue by mhamann** [ReSwift/ReSwift#495]
I'm writing some instrumented tests where I need to set up an initial store state, then run an action, and then check the store's state after the action completes to ensure that the correct state got set afterward.

I thought that by ensuring all of the state dispatchings were on the main thread would essentially make this synchronous, but it appears my understanding may have been incorrect.

Is there a way to write code like the following (simplified)?

```swift
// MyStore.swift
let thunkMiddleware: Middleware<RowndState> = createThunkMiddleware()
let store = Store(
    reducer: myReducerWithNoSideEffects,
    state: InitialState(),  // isLoading: false by default
    middleware: [
        thunkMiddleware
    ]
)

// MyTest.swift
store.dispatch(MyAction(isLoading: true))

// A somewhat stupid assertion, but just to illustrate
XCTAssertTrue(store.state.isLoading, "isLoading should be true, initially")
```

**Comment by mjarvis** [comment]
As long as your middleware is not intercepting / async'ing your action, then yes, this code and your understanding will be correct.

**Comment by mhamann** [comment]
Thanks!
