### ISSUE TITLE
How to use a state on recursive screens?

### ISSUE THREAD

**Issue by toomozoo** [ReSwift/ReSwift#499]
For example, when you have `UserState` in `ViewControler` that displays a user and posts, what is the best practice to do?

- UserViewController -> UserViewController -> UserViewController...
- UserViewController -> PostViewController -> UserViewController -> PostViewController...

```
struct UserState: Equatable {
    var user: User
    var posts: [Post] = []
}
```

Can I implement something like below? 

```
struct AppState: Equatable {
    // var user = UserState()
    var users: [UserState] = []
}
```

I am new to ReSwift and would appreciate any advice you could give me :bow:

**Comment by DivineDominion** [comment]
That sounds about right to get started!

You can find similar ideas expressed in discussions about the old Router:
https://github.com/ReSwift/ReSwift-Router

**Comment by toomozoo** [comment]
@DivineDominion 

Thank you for your comment!
I checked [ReSwift-Router](https://github.com/ReSwift/ReSwift-Router) but I could not figure out how to implement recursive way...
What you are saying is that I should refer to [Route with parameters](https://github.com/ReSwift/ReSwift-Router/issues/3)?

**Comment by DivineDominion** [comment]
To be honest I'm not sure about which issue in particular it was, or if it was something that came up every now and then 🤔

https://github.com/ReSwift/ReSwift-Router/issues?q=is%3Aissue+is%3Aclosed+multiple

So each same controller's route would need some "identifier" that is unique to disambiguate. 

Anything you find that can help other newcomers to ReSwift-Router in a position similar to yours, please consider taking notes and sharing the result in a PR for a readme or documentation example!

**Comment by DivineDominion** [comment]
https://www.jessesquires.com/blog/2022/12/15/powerful-navigation-api/ Possibly useful to let UIKit's nav controller handle the diffing and map an array of states to UIViewControllers
