### ISSUE TITLE
Counter Example link broken

### ISSUE THREAD

**Issue by mccannmax** [ReSwift/ReSwift#52]
https://github.com/ReSwift/CounterExample is 404-ing :(

**Comment by sendyhalim** [comment]
hi @mccannmax the link should be https://github.com/ReSwift/CounterExample-Navigation-TimeTravel if I'm not mistaken :beers: 

PR https://github.com/ReSwift/ReSwift/pull/53

**Comment by Ben-G** [comment]
Yep! Fixed by #53. Thanks @mccannmax for pointing out and thanks @sendyhalim for fixing it!
