### ISSUE TITLE
Store subscription promotes retain cycles in view controllers

### ISSUE THREAD

**Issue by russbishop** [ReSwift/ReSwift#62]
The natural way to approach store subscription is to subscribe in `viewDidLoad`, then unsubscribe in `deinit`. Because the `Store` holds a strong reference to the VC this promotes a retain cycle. I feel like this is a bear trap that people will repeatedly step in so maybe it is worth discussing potential solutions. 

1. Tell people not to hold a reference to the store, just access it as a global. This seems like a bad idea and bad design.
2. Tell people to hold a `weak` reference to the store. This relies on everyone doing the "right thing" which we already know they don't do.
3. Have the store hold subscribers as a `weak` reference (I have a `WeakBox` that could be used for this). This means putting unsubscribe in the `deinit` should work just fine to keep the subscriber array clean. When dispatching if we encounter a `nil` subscriber we could remove it or assert depending on whether we consider this a programmer error or not.
4. Tell people to subscribe in `viewWillAppear` and unsubscribe in `viewWillDisappear`. 

It might be obvious but I lean heavily toward 3 because it eliminates a headache for users of the library and allows them to rely on the existing UIKit/AppKit mechanisms for managing View Controller lifetimes. My temporary workaround is to unsubscribe from `viewWillDisappear` but that is problematic for VCs that will in fact re-appear and 4 means you can't react to state changes if you aren't on-screen.

I'm happy to submit a PR for this one if there is consensus on fixing it.

**Comment by Ben-G** [comment]
Hm.. I might be missing something. But shouldn't unsubscribing in `deinit` break the strong reference from the `Store` to the VC?

**Comment by Ben-G** [comment]
Ah, got it :smile: `deinit` won't ever be called because the store holds a strong reference to the VC.
I personally haven't run into this since I use option 4. by default.

But this definitely is an issue that should be fixed. Users of the library would not naturally expect the store to keep a strong reference to the subscribers.

A PR would be welcome :smiley:

**Comment by russbishop** [comment]
@Ben-G Because of the strong reference in the store subscription and the VC's `var store: StoreType` property, when the VC is dismissed (say by popping from the nav stack) there is still a live reference so `deinit` is never called.

**Comment by DivineDominion** [comment]
In another app I circumvented issues like these by adhering to the convention of not subscribing/unsubscribing `self` ever, only child components. Same for notifications.
