### ISSUE TITLE
Have you thought about Protocol Buffers/Flat Buffers for the action serialization?

### ISSUE THREAD

**Issue by aandr** [ReSwift/ReSwift#81]
Replacing JSON with Protocol Buffers would remove the manual serialization step and it would also make it easier to integrate with an action-oriented backend. If you think that's a good idea, I'd be happy to take a stab at it.

**Comment by Ben-G** [comment]
@aandr I'm definitely open to this idea. So far using JSON simply was the easiest option. The entire recording part is still a quick hack. 

IMO the biggest issue we need to solve is making it more convenient to serialize/deserialize actions. I think if we want to stick with pure Swift we can only accomplish this with code generation. I don't think that JSON vs. Protocol Buffers would have any major differences for optimizing this step.

However, I'm definitely curios to see what your attempt would look like!

**Comment by davidlawson** [comment]
You can do a surprising amount with introspection in Swift, these functions can encode a `struct` or `class` to and from a `[String: Any]`:
https://github.com/davidlawson/SwiftKVC/blob/master/SwiftKVCTests/SwiftKVCTests.swift#L60-L98

The only disadvantage is that you would need to keep an array of `Action.Type` around for the deserialisation process. Perhaps nicer than code generation though?

A Swift JSON library (e.g. SwiftyJSON – using NSJSONSerialization uses non-Swift objects) could then be used to persist the data.

Another similar library: https://github.com/sagesse-cn/swift-serialize

**Comment by Ben-G** [comment]
I'm closing this for now, due to staleness.
