### ISSUE TITLE
Automatic serialisation & deserialisation of actions and state

### ISSUE THREAD

**Issue by davidlawson** [ReSwift/ReSwift#85]
You can do a surprising amount with introspection in Swift, these functions can encode a `struct` or `class` to and from a `[String: Any]`:
https://github.com/davidlawson/SwiftKVC/blob/master/SwiftKVCTests/SwiftKVCTests.swift#L60-L98

The only disadvantage is that you would need to keep an array of `Action.Type` around for the deserialisation process. Perhaps nicer than code generation though?

A Swift JSON library (e.g. SwiftyJSON – using NSJSONSerialization uses non-Swift objects) or equivalent could then be used to persist the data.

(This may also work well for serialising state as well as actions.)

Another similar library: https://github.com/sagesse-cn/swift-serialize

Limitations with this approach:
– deserialisation requires there to be an `init` method with no parameters (created by default if initial values are provided)
– serialisation does not support implicitly unwrapped optionals
– deserialiser requires array of action types to work
– seems to be fighting the language a bit

**Comment by Ben-G** [comment]
@davidlawson Thanks a lot for sharing. The approach is really clever, but as some of the limitations show also fairly fragile. I would also expect this to break fairly frequently, as Swift is updated.

I personally still feel code generation would be a better option but I'm very happy to have a discussion about it :smiley:

**Comment by davidlawson** [comment]
I agree! Another option I've looked into is https://github.com/evermeer/EVReflection. It works well with Swift but unfortunately it requires that the objects serialised/deserialised subclass EVObject which is a subclass of NSObject.

**Comment by davidlawson** [comment]
And another option :) https://github.com/tomlokhorst/swift-json-gen

**Comment by AlexLittlejohn** [comment]
Going the reflection route with [Mirror](https://developer.apple.com/library/ios/documentation/Swift/Reference/Swift_Mirror_Structure/index.html) might be a solution. Its 100% swift and part of the core libs.

**Comment by DivineDominion** [comment]
(If we support this in the main lib, we would be using Codable nowadays. My suggestion for posterity: implement a `ReplaceAppState` action yourself and use whatever you like)
