### ISSUE TITLE
Make last action available to subscribers

### ISSUE THREAD

**Issue by vfn** [ReSwift/ReSwift#86]
While implementing Redux I started seeing the propagation of messages being sent to subscribers as the number of actions and state properties increase.

For a small app, where just a few properties represent the state of the app, and the complexity of re-rendering the new state is not a big deal, it doesn't hurt to just update the UI or do a quick comparison to see if an update is needed.

For cases where updating the UI or comparing the previous with the current state is a complex task, it would be useful to allow subscriber to know what action has been triggered and leave to the subscriber to decide whether it should re-render or not.

The issue https://github.com/reactjs/redux/issues/580 has been closed by the redux team as it doesn't fit with the React paradigm. Unfortunately most of us cannot rely on a framework like React to do the diff and answer the question `What should be rendered again?`.

With this in mind, I'd like to propose or a change to the `AnyStoreSubscriber`/`StoreSubscriber` to have the state added to the functions...

```swift
public protocol AnyStoreSubscriber: class {
    func _newState(state: Any, actionType: Action.Type)
}

public protocol StoreSubscriber: AnyStoreSubscriber {
    typealias StoreSubscriberStateType

    func newState(state: StoreSubscriberStateType, actionType: Action.Type)
}

....


// MARK: - StoreSubscriber methods on a random subscriber

extension MyRandomViewController: StoreSubscriber {

    func newState(state: AppState, actionType: Action.Type) {
        guard actionType == MyRandomAction.self else { return }

        // Handle new state
    }

}

```

...or the addition to the documentation on how to appropriately handle this necessity. One way would be to add a `lastAction` property to the state.

Any thoughts?

**Comment by Ben-G** [comment]
Hey @vfn, thanks for bringing this up. I think making the latest action available potentially leaks to much information to subscribers. I like the idea that the view layer written with ReSwift will always only respond to changes in the state, not any other input.

You certainly could extend your state to always capture the action and store it as part of the app state, but I feel like this might not be a good idea. You add a dependency on an a piece of state that changes very frequently which will make your code harder to understand.

To address your original issue:

> For cases where updating the UI or comparing the previous with the current state is a complex task, it would be useful to allow subscriber to know what action has been triggered and leave to the subscriber to decide whether it should re-render or not.

I have so far always went down the route of comparing states & only updating the UI if I find relevant differences in them. It seems like the step of comparing current and previous state should never be very complex (but I might be missing a relevant example).

Could you share an example of an expensive state comparison? I'm sure that would help this discussion.

Thanks for the idea!

**Comment by vfn** [comment]
Hi @Ben-G ,

Thank you for the explanation. I haven't found any performance issues so far, although the amount of data held by the state is not a big deal. It might be that I'm too attached to other design principals and not fully diving into this new architectural approach.

I'll close the issue and I might reopen it or add some more info in the future when I have the opportunity to work with a more complex app state.

Cheers
