### ISSUE TITLE
State change with new array items

### ISSUE THREAD

**Issue by eschan** [ReSwift/ReSwift#93]
If your state contains an array property, and you append a new item to the array, is there a way to determine which item was added to the state? Is there a way to get a diff between previous state and the new state?

**Comment by Ben-G** [comment]
Hey @eschan,

figuring out which elements have changed is not directly built into ReSwift. However, there are different ways how you can accomplish this.

> Is there a way to get a diff between previous state and the new state?

Yes, however not through a built-in method. You're subscriber can keep a reference to the previous state. That is e.g. how `ReSwiftRouter` works currently: https://github.com/ReSwift/ReSwift-Router/blob/master/ReSwiftRouter/Router.swift#L17

That said, it might be worth adding this directly to the library. Especially when working with UIKit it's often necessary to keep the previous state around for diffing. Another alternative would be building a middleware that takes care of it. Redux has some examples: https://github.com/inakianduaga/redux-state-history.

Lastly, you could use a custom data structure, such as `ObservableArray` (part of the Bond library: https://github.com/SwiftBond/Bond/blob/master/Bond/Core/ObservableArray.swift), to keep track of individual state changes in your array, and add these to your state in some way.

----

There are many possible options, most likely you will want to keep store the previous state in your `Subscriber` and then diff the two arrays (something like Dwifft will help you with that: https://github.com/jflinter/Dwifft)

Hope this helps!

**Comment by eschan** [comment]
thanks for the reply @Ben-G 

I ended up using a combination of RxSwift and AsyncCreator callbacks to manage state transitions and side-effects. 

thanks!

side note: i see that project is now 1.0, congrats!
